B02 - 카테고리 보기 api
woowacourse-teams/2021-botobo pull request #24
Opened 2021-07-07 09:18 UTC by pkeugine

closes #21 

## 작업내용

모든 카테고리 정보를 가지고 오는 api 구현

## 주의사항

없음

2021-07-07 09:30 UTC, seovalue commented on backend/src/main/java/botobo/core/category/application/CategoryService.java
> +
불필요한 한줄 띄우기 아닐까요?

2021-07-07 09:31 UTC, seovalue commented on backend/src/main/java/botobo/core/category/dto/CategoryDto.java
> +
인수테스트가 없네요 ~^^
DTO에 빈 생성자와 게터가 없어서 Controller에서 바인딩이 안될 것 같아요!

2021-07-07 09:34 UTC, seovalue requested changes
코멘트 남겼는데 확인 부탁드립니다!

2021-07-07 09:45 UTC, ohjoohyung requested changes

2021-07-07 09:45 UTC, ohjoohyung commented on backend/src/main/java/botobo/core/category/dto/CategoryDto.java
> +public class CategoryDto {
요청 관련된 dto는 ~Request, 응답 관련된 dto는 ~Response로 통일하는게 좋을거 같아요!

2021-07-07 09:45 UTC, ohjoohyung commented on backend/src/main/java/botobo/core/category/application/CategoryService.java
> +@Transactional
메서드에도 같이 @Transactional을 명시할거면 클래스에는 readOnly=true로 바꾸는게 어떨까요?

2021-07-07 10:16 UTC, pkeugine commented on backend/src/main/java/botobo/core/category/application/CategoryService.java
> +
저와 중간곰이 말했을 때 리턴과 로컬변수 사이에 빈 줄을 넣는게 읽기가 더 쉽다고 동의하여 한 줄 추가했습니다!

2021-07-07 10:16 UTC, pkeugine commented on backend/src/main/java/botobo/core/category/dto/CategoryDto.java
> +
네!!!!

2021-07-07 10:16 UTC, ggyool commented on backend/src/main/java/botobo/core/category/dto/CategoryDto.java
> +public class CategoryDto {
반영했습니다👍

2021-07-07 10:16 UTC, ggyool commented on backend/src/main/java/botobo/core/category/application/CategoryService.java
> +@Transactional
반영했습니다👍

2021-07-08 01:08 UTC, seovalue commented on backend/src/main/java/botobo/core/category/ui/CategoryController.java
> +@RestController
예시 코멘트 입니당

2021-07-08 01:47 UTC, seovalue approved these changes
어프루브 드립니다!

2021-07-08 01:47 UTC, ohjoohyung approved these changes
확인했습니다! 이제 머지하시면 될거같아요~~

2021-07-08 02:11 UTC, merged