S02 - 검색 페이지 UI 및 기능을 구현한다
woowacourse-teams/2021-botobo pull request #334
Opened 2021-08-07 07:20 UTC by dudtjr913

closes #327 

## 작업 내용
- 검색 페이지 UI 구현
- 검색 페이지 검색 기능 구현 => 공유 문제집으로 연결되는 것 까지
- 공유 문제집(PublicWorkbookList) 인피니티 스크롤 적용(Intersection Observer)
- usePublicSearch 훅 생성(공유 문제집 검색 - searchForPublicWorkbook, 태그/작성자와 같은 키워드 검색 - searchForKeyword)
- PublicSearchList 컴포넌트를 구현해 태그/작성자에 대한 처리를 했음
- publicSearchList와 publicWorkbookList가 상태를 너무 많이 props로 전달받고 있어서 전역으로 관리되고 있는 searchKeyword와 searchType은 각각의 컴포넌트에서 받아서 사용하기로 했음
- 검색 결과 페이지 스켈레톤 구현
## 주의 사항
- 좋아요 기능이 구현되지 않아서 좋아요 필터링 불가
- 양이 많음
- 기존에는 검색을 한 뒤 이전 페이지로 돌아갈 때, 검색어가 그대로 유지되고 있었지만 현재는 지원하지 않고 있음. 이유는 키워드를 검색하기 위해 ad를 검색했을 때, admin이 나오게 되고 admin으로 서버에 요청을 보내기 위해 키워드(searchKeyword)를 ad에서 admin으로 변경하게 되는데, 이 경우 검색 페이지로 나오게 되면 admin이 들어가있게 됨. 어떻게 하는 것이 좋을지 카일의 의견을 듣고 싶음

2021-08-07 10:19 UTC, GwangYeol-Im requested changes
파일 개수 많을 거라고 해서 잔뜩 겁먹고 읽기 시작했는데, 생각보다 대부분의 파일은 중요하지 않았고 코드 또한 깔끔하게 잘 짜줘서 이해하는데 어렵지 않았어요 ㅎㅎ 다만 현재 제 쪽에서 검색 관련 요청이 잘 되지를 않는 것 같아서(ㅠ..) UX 확인은 디토랑 같이 해야할 것 같네요!

그리고 infinity scroll 을 문제집에만 적용을 한 이유와 Observer 구현 방식에 대한 강의도 듣고 싶네요 ㅋㅋ 이따 디스코드로 부탁해요~~

2021-08-07 10:19 UTC, GwangYeol-Im commented on frontend/src/pages/PublicSearchPage.tsx
> +const searchTabList = [
`searchTabInfos` 혹은 `searchTabs`는 어떨까요? 그동안 배열 네이밍에서 List는 잘 안썼던 것 같아서 개인적으로 제안드립니다~~

2021-08-07 10:19 UTC, GwangYeol-Im commented on frontend/src/pages/PublicSearchPage.tsx
> +const searchTabList = [
여담이지만 탭 관리 맘에 드네요 👍🏻

2021-08-07 10:19 UTC, GwangYeol-Im commented on frontend/src/pages/PublicSearchPage.tsx
> +                      searchTabList.find((item) => item.id === id) ??
위의 네이밍을 수정해주면 여기도 item보다 좀 더 괜찮은 이름을 줄 수 있을 것 같아요!

2021-08-07 10:19 UTC, GwangYeol-Im commented on frontend/src/hooks/usePublicSearch.ts
> +
이 부분을 세 개의 if문으로 처리하게된 이유를 들어보고 싶어요!!

2021-08-07 10:21 UTC, GwangYeol-Im commented
추가로 주의사항 세 번째 항목은 저도 동의합니다!! 저 개인적으로는 검색 결과에서 검색 페이지로 넘어갈 때는 검색어가 없는 게 더 자연스러운 것 같아서 오히려 좋네요 ㅎ.ㅎ 그대로 가시죠👍🏻

2021-08-07 10:26 UTC, dudtjr913 commented on frontend/src/hooks/usePublicSearch.ts
> +  >([]);
할 생각도 안해봤어요 ㅋㅋㅋ 저번에 모달에서 한번 관련 상태들만 모아서 객체로 관리하려고 했다가 코드가 더 더러워졌던 것을 봐서 생각 안해본 것 같아요. 한번 도전해볼게요!

2021-08-07 10:28 UTC, dudtjr913 commented on frontend/src/hooks/usePublicSearch.ts
> +      console.error(error);
넵~

2021-08-07 10:28 UTC, dudtjr913 commented on frontend/src/hooks/usePublicSearch.ts
> +      console.error(error);
의도한 건 아니였고, 기존에 위에 있던 코드는 원래 usePublicWorkbook인가?? 에 있던 코드인데요, 거기에서 저런 순서로 있어서 그냥 복사한거에요!! 바꿔놓을게요~

2021-08-07 10:29 UTC, dudtjr913 commented on frontend/src/pages/PublicSearchPage.tsx
> +    window.addEventListener('popstate', resetKeyword);
넴 아까 하나 지우다가 공백도 지워버렸네요! ㅋㅋㅋ

2021-08-07 10:29 UTC, dudtjr913 commented on frontend/src/pages/PublicSearchPage.tsx
> +const searchTabList = [
맞네요... list를 안썼었군요. 저도 컨벤션 파괴자네요? ㅋㅋㅋㅋㅋㅋㅋㅋ 혼자할 땐 list를 많이 쓰다보니 습관적으로 나온 것 같아요. 고치겠습니당

2021-08-07 10:30 UTC, dudtjr913 commented on frontend/src/pages/PublicSearchPage.tsx
> +                      searchTabList.find((item) => item.id === id) ??
함께 바꾸겠습니다~

2021-08-07 10:37 UTC, dudtjr913 commented on frontend/src/hooks/usePublicSearch.ts
> +
3개의 분기가 나오게 되는데, 각각을 메서드로 만들기는 싫고, 추상화는 하고 싶은데 어떻게 해야할지 잘 모르겠어서 일단은 if문으로 처리했습니다. switch문과 if문을 고민하다가 아직은 3개밖에 되지 않아 switch문이 불필요하다고 생각해서 if문으로 처리했습니다.

예전에 filter에서 했던 것처럼 객체 안에 메서드를 두고 해볼까도 생각했지만 type === name일 때는 hook 안에 있는 메서드를 호출해야 하기 때문에 그러면 hook 안에 객체를 선언해야 할까?? hook 안에 객체 선언하면 계속 생성돼서 좋지 않을 것 같은데... 이런 생각들을 하다가 if문으로 처리했습니다. 

지금 코멘트 남기면서 생각해보니 if(type === 'name')은 그대로 두고, 밑에 2개는 객체로 빼서 사용해도 될 것 같네요! 이따 디스코드로 얘기해봐요~!

2021-08-07 10:40 UTC, dudtjr913 commented
이따 디스코드에서 얘기하겠지만 간략하게만 제 생각을 말씀드릴게요!
 infinity scroll 을 문제집에만 적용한 이유 - 태그와 작성자는 항상 최대 10개까지만 보여주기로 했기 때문에 infinity scroll이 필요하지 않았습니다. 즉, 문제집만 무한정으로 받을 수 있는 구조였고, 각각의 페이지에 적용할까 하다가 같은 로직이 2번 쓰이게 돼서 어쩌피 이건 문제집 한정 기능일 것 같다고 생각해서 문제집에만 적용해놓았습니다.(페이지는 PublicSearchPage, PublicSearchResultPage 두 군데에서 사용해야 했습니다.)

 Observer 구현 방식은 이따 같이 얘기해보아요~ 저도 어려워서 ㅎㅎ;;;

2021-08-07 12:22 UTC, GwangYeol-Im commented on frontend/src/hooks/usePublicSearch.ts
> +  >([]);
ㅋㅋㅋ 넵 너무 무리하진 않아도 돼요~~

2021-08-07 12:23 UTC, GwangYeol-Im commented on frontend/src/pages/PublicSearchPage.tsx
> +const searchTabList = [
ㅋㅋㅋㅋㅋㅋ혼자 하면 컨벤션 파괴자 인정.. 이렇게 잡아주면 되죠 뭐 ㅎㅎ

2021-08-07 12:25 UTC, GwangYeol-Im commented on frontend/src/hooks/usePublicSearch.ts
> +
넵 이 부분은 코드 처리 흐름을 같이 얘기해보고 판단해도 좋을 것 같아요!!

2021-08-09 06:00 UTC, GwangYeol-Im approved these changes
수정사항 모두 확인했습니다! 수많은 조건 분기를 처리 하면서도 코드의 가독성을 놓치지 않기 위해 많은 노력을 기울인 흔적이 보이네요 :) console.log 남아있는 거 말고는 모두 좋아요. 👍🏻 다만 스스로에게 한가지 아쉬웠던 점은, 코드의 양이 상당하다보니 방법론보다는 스타일적인 부분이나 잔실수에 대한 피드백만 드리게 되는 것 같아요 ㅜㅜ 

이러한 사항을 예측하지 못한 제 실수도 어느정도 있다고 생각합니다 ㅎㅎ 둘다 코드 리뷰가 처음이다보니 충분히 마주칠 수 있었던 상황이었던 것 같아요. 다음 스프린트에서는 PR의 양도 서로 논의 후에 티키타카 많이 나눠봐요~!~!

2021-08-09 06:03 UTC, dudtjr913 commented on frontend/src/pages/PublicSearchPage.tsx
> +                console.log(target.value);
감사합니다

2021-08-09 06:03 UTC, dudtjr913 commented
다음에는 잘 나눠서 피알 올릴게요! 코드 리뷰하느라 수고하셨습니다~!~!~!👍👍😍😍

2021-08-09 06:08 UTC, merged