F27 - 마주친 횟수를 표시한다(퀴즈 페이지 및 카드 모아보기 페이지)
woowacourse-teams/2021-botobo pull request #350
Opened 2021-08-09 10:05 UTC by dudtjr913

closes #347 

## 작업 내용
- 마주친 횟수 표시(풀어본 횟수)
- 퀴즈 페이지, 퀴즈 결과 페이지, 모아보기 페이지
## 주의 사항
- 없음

2021-08-09 13:02 UTC, GwangYeol-Im requested changes
코드, 모바일 UI 모두 확인했습니다! 고칠 부분은 딱히 없네요~ 다만 현재, 노트북에서 반응형으로 확인해보면 카드가 넘어갈 때 사라지는 오류가 있는데 이 부분 확인이 된건가요? 👀

2021-08-09 19:43 UTC, dudtjr913 commented
저도 아까 확인하다가 발견했어요. 문제는 초기에만 width를 정해서 set해주고 있었기 때문에 그래서 resize 이벤트를 걸어서 해결했습니다. 조금 고민 중인 부분은 resize에 debounce를 걸 것인지가 고민되는데요, resize는 어쩌피 많이 발생하는 이벤트가 아니라서 굳이 걸지 않아도 된다고 생각해서 일단은 걸지 않았습니다.

2021-08-10 06:30 UTC, GwangYeol-Im approved these changes
리사이즈 버그를 이미 수정해 놓았는데, 제가 확인을 미처 못했네요. ㅠ 현재 처리에서 디바운스가 필요하다고 생각했던 이유가 있을까요? 직접 확인해보았을 때 정상적으로 동작되고 디토 말대로 화면 리사이징은 자주 할 것 같진 않아 보이네요~ 코드 수정 형태도 지금이 적당한 것 같아 이만 approve 남겨놓을게요!

2021-08-10 08:30 UTC, dudtjr913 commented
디바운스가 필요하다고 생각하진 않았고, 리사이즈가 일어나는 것이 스크롤과 비슷하게 한번에 많이 발생하는 이벤트라고 생각해서 의견을 물어봤습니다~! 저도 안해도 된다고 생각해요👍

2021-08-10 10:51 UTC, GwangYeol-Im commented
좋습니다 ㅎㅎ 충돌만 해결해주시고 바로 머지해도 괜찮을 거 같아요!

2021-08-10 11:29 UTC, merged