S04 - 검색 페이지에서 초기 문제집 100개를 보여준다
woowacourse-teams/2021-botobo pull request #453
Opened 2021-09-01 09:03 UTC by GwangYeol-Im

closes #435 

## 작업 내용

- 메소드 이름 사용 위해 기존 getPublicWorkbookAsync -> getSearchResultAsync 변경
- 검색 페이지 진입 시 초기 데이터 100개 렌더링

## 주의 사항

- hook 분리는 로직 정리 후 진행 예정
- 확인 위해서 feature/W01-B pull
- 로드 시간이 오래 걸려 Suspense 사용 위해 recoil 상태로 빼놨는데 이 부분에 대해 논의 필요할 것 같아요!

2021-09-02 02:44 UTC, dudtjr913 requested changes
코드 잘 봤습니다~ 딱히 문제될만한 부분이 보이지 않고 깔끔하네요.
궁금한 것을 코멘트에 남겨 놓았는데, 댓글 달아주세요!!

고생하셨습니다~

2021-09-02 02:44 UTC, dudtjr913 commented on frontend/src/pages/PublicSearchPage.tsx
> +  const updateWorkbooks = useResetRecoilState(publicWorkbookState);
해당 페이지에 진입할 때마다 초기화를 해주는 걸 보니 캐싱 목적이 아닌 것 같은데 리코일을 사용한 이유가 있을까요?
로딩 문제 때문이라면 다른 페이지에서 캐싱 목적이 아닐 때 지역 상태로 가지고 있는 부분도 모두 리코일로 변경해야 할까요? 의견을 듣고싶어요!

아, 주의 사항에 써있었네요? 로딩이 오래 걸려서 그런 것이라면 기존에 하던 방식대로 loading일 때 스켈레톤 보여주는 걸로 하면 어떤 문제가 있었나요?

2021-09-02 02:44 UTC, dudtjr913 commented on frontend/src/pages/PublicSearchPage.tsx
> -  }, [stickyTriggerRef.current]);
이거는 왜 삭제하셨나요? 랜더링이 될 때마다 항상 실행될 것 같은데, 위험한 코드인 것 같아 보여요!

2021-09-02 08:22 UTC, GwangYeol-Im commented on frontend/src/pages/PublicSearchPage.tsx
> +  const updateWorkbooks = useResetRecoilState(publicWorkbookState);
> 로딩 문제 때문이라면 다른 페이지에서 캐싱 목적이 아닐 때 지역 상태로 가지고 있는 부분도 모두 리코일로 변경해야 할까요? 의견을 듣고싶어요!

저도 디토의 생각과 동일해요! 사실 저도 구조상 어느정도 모순이 있다는 걸 염두에 두고 코드를 작성하게 되어 리뷰 때 디토랑 같이 얘기해보고 싶었어요~ 일단 체감상 100개를 모두 가져와서 렌더링까지 소요되는 시간이 꽤 오래 걸려서 생각의 흐름이 점점 데이터를 pre-fetch 해오는 게 좋겠다로 이어지게 되었어요. (그래서 recoil 상태로 임시 배치 했지만 역시 수정 해야겠네요)

이 페이지에서만 쓰는 상태이기 때문에 저도 지역 상태로 두어야 한다는 쪽이고 데이터를 캐시하지 않는 이상 쪼개서 받아와야 할 것 같은데 디토의 생각은 어떠신가요?

2021-09-02 08:23 UTC, GwangYeol-Im commented on frontend/src/pages/PublicSearchPage.tsx
> +                  setSessionStorage(STORAGE_KEY.PUBLIC_WORKBOOK_ID, id);
아 맞네요!! 좋은 방향입니다 👍🏻 디토의 리뷰는 매번 제가 놓치고 있는 것들을 상기시켜줘서 좋은 것 같아요. 꼼꼼한 리뷰 고마워요~

2021-09-02 08:33 UTC, GwangYeol-Im commented on frontend/src/pages/PublicSearchPage.tsx
> -  }, [stickyTriggerRef.current]);
아 이 부분은 옵저버가 예상대로 행동되지 않아 임시 대처했던 코드였는데 정확한 경위를 파악하지 못하고 그대로 올려버렸네요,, 원인을 먼저 알아보고 그 후에 수정이 이루어졌을 때 이유와 함께 올릴게요!

2021-09-02 08:34 UTC, GwangYeol-Im commented on frontend/src/pages/PublicSearchPage.tsx
> +  const updateWorkbooks = useResetRecoilState(publicWorkbookState);
아 일단 백엔드 쪽에서 알고리즘 개선을 해보고 있으니 좀 더 진행해보고 다시 말씀드릴게요!!

2021-09-02 08:36 UTC, GwangYeol-Im commented on frontend/src/pages/PublicSearchPage.tsx
> -  }, [stickyTriggerRef.current]);
일단 문제는 페이지에 진입 했을 때 보여야할 데이터가 생기면서 옵저버가 처음부터 ref를 관측하지 못해 계속 sticky상태가 유지되어버리는 버그를 발견했어요! 왜 그런건지는 좀 더 살펴보겠습니다~

2021-09-03 09:23 UTC, GwangYeol-Im commented
데이터를 지역상태로 바꿔준 뒤, intersection observer의 의존성을 isLoading으로 두니 기존의 버그를 해결할 수 있었습니다! input이 바뀔 때마다 다시 트리거되는 부분도 문제 없을 것 같아요~

2021-09-03 10:09 UTC, dudtjr913 approved these changes
지금 PublicSearchPage에서 안쓰는 recoil이 import되고 있는 것만 삭제하면 될 것 같아요. 좋네요! ref가 렌더링을 발생시키지 않아서 생긴 문제였을까요? 아직도 미스테리네요...ㅜㅜ 

아 그리고 isLoading의 초기값을 true로 하는 방법을 예쩐에 로딩 고민할 때 해보지 않았었나요? 그때 true로 했다가 분명 무슨 이슈가 터져서 다시 바꿨던 것 같은데.... 그게 아니라면 다른 페이지에서도 모두 true로 설정해도 좋을 것 같아요! 처음부터 true로 해두면 Suspense랑 거의 비슷(데이터를 미리 가져오는 것만 빼면)하다고 하면서 좋아하다가 무슨 이슈 때문에 취소했던 것 같은데 이슈가 생각이 안나네요... 혹시 기억나시나요 ?

우선 Approve는 하겠습니다!

2021-09-03 11:20 UTC, merged