UI17 - 검색 상세 페이지에서 바텀 모달을 추가한다(태그, 작성자 필터링)
woowacourse-teams/2021-botobo pull request #454
Opened 2021-09-02 15:21 UTC by dudtjr913

closes #439 

## 작업 내용
- 검색 상세 페이지에서 바텀 모달 구현
- 모달을 열 때 바디가 스크롤되던 버그 해결(document.body.style에 접근했는데, 다른 방법이 있으면 알려주세요..ㅠㅠ)
- 필터링에 스티키를 적용했고, 필터링이 많아서 2줄이 되면 자리를 많이 차지하는 것 같아서 횡스크롤이 가능하게 구현했습니다.
횡스크롤을 할 때 스크롤바를 없앴는데, 데스크탑일 때 스크롤바가 없으면 혼란을 줄 수 있을 것 같아서 데스크탑인 경우에는 스크롤바를 추가해주었습니다. (isMobile을 사용했습니다.) 사실 데스크탑일 때 그만큼 width를 줄일 사람은 없을 것 같지만 혹시 모르는 상황에 대비하기 위해서 이렇게 구현했습니다.
- isMobile을 즉시실행함수로 실행해서 함수가 아닌 값으로 변경했습니다. 이유는 isMobile은 앱 처음 진입할 때만 검사하면 이후에 바뀌지 않는다고 생각했기 때문입니다. 핸드폰으로 보다가 갑자기 컴퓨터로 바뀔 수는 없다고 생각했어요. 그리고 isMobile에서 로직을 많이 변경했는데, 기존에 사용하던 navigator.platform은 deprecated되었다고 해요... [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/platform) 그래서 알아보다가 navigator.userAgent가 있었고, 이건 접속한 단말기의 환경을 알려주는 것이라고 해요. 근데 여기에서 또 문제가 있었는데 아이패드가 데스크탑화 한다고 2019년부터 밀어붙이다가 정말로 최신 아이패드를 조회해보면 환경이 IPad가 아니라 Macintosh, Mac OS라고 나오고 있어요. 데스크탑이랑 구분할 수가 없게 되었어요 ㅠㅠ(구글은 iPad라고 나오는데 사파리에서는 Macintosh라고 나오네요... 하 나쁜 사파리,,, 애플,,,) 
그래서 차이가 나는 부분인 Macintosh로 비교를 하도록 변경했어요. Macintosh면 태블릿일 수도 있고 맥북일 수도 있고 맥일 수도 있기 때문에 이제 다시 터치 여부로 판단하기 위해서 navigator.maxTouchPoints로 비교를 했어요. 1 이상이면 터치가 되는 것으로 터치가 된다면 태블릿으로 볼 수 있을 것 같아서요! 다른 방법이 있으면 제시해주셔도 좋아요😍😍
## 주의 사항
- 기능은 하지 않았습니다.

2021-09-03 06:30 UTC, GwangYeol-Im requested changes
코드 잘봤습니다 디토! UI 부분 작업이기도 했고 전반적으로 코드를 잘 작성해주셔서 좋았습니다 :) 피알을 자세하게 잘 작성해줘서 의도를 읽는 게 어렵지 않았어요 ㅎㅎ 동시에 제 자신의 코드에 대해서는 너무 리뷰어의 이해만 바란 건 아닌가 반성하게 되었네요 🥺 리뷰는 상세 코멘트로 남겨두었습니다!

p.s. 작성 내용에 써주신 부분은 모두 동의합니다~ 그대로 가도 좋을 거 같아요 ㅎㅎ
\+ p.s. 아 그리고 UX 부분에서도 제안하고 싶은 부분이 있는데요! 현재 필터 데이터를 선택할 때 페이지에서 초기화 버튼 렌더링이나 선택된 데이터 내용이 실시간으로 바뀌는게 보이던데, 이것도 확인을 눌렀을 때 일괄적용하면 어떨까요?

2021-09-03 06:30 UTC, GwangYeol-Im commented on frontend/src/components/MultiFilterSelector.tsx
> +    data.map((value) => ({
PublicSearchResult 페이지에서 filter data를 받아와서 `data`와 `selectedData`의 내용을 모아두면 어떨까요?
```ts
data: [
  {
    id: number,
    name: string,
    isSelected: boolean
  }
]
```

이렇게 생각했던 이유는 다음과 같은데요.

- 해당 코드 라인에서 상태 데이터를 얻기 위한 알고리즘이 n^2 의 복잡도를 가지는 듯함
- 페이지와 이 컴포넌트에서 동일한 특징을 가진 데이터를 사용하는 것처럼 보임 (데이터, 선택 여부)

사실 페이지와 이 컴포넌트 사이의 흐름을 고려하면서 이 부분을 언급하는 게 맞나 싶어 리뷰 시간이 좀 길어졌던 것 같아요 ㅠ 그래도 가능만 하다면 상태의 흐름을 조금 더 간결하게 가져갈 수 있지 않을까는 생각으로 제안해봅니다!

2021-09-03 06:30 UTC, GwangYeol-Im commented on frontend/src/components/MultiFilterSelector.tsx
> +  data: { id: number; name: string }[];
여기는 따로 인터페이스 처리를 안해줬던 이유가 있었을까요? 😊

2021-09-03 06:35 UTC, dudtjr913 commented on frontend/src/contexts/ModalProvider.tsx
> +    document.body.style.overflow = 'hidden';
좋게 봐주셨다니 감사합니다 ㅎ

2021-09-03 06:39 UTC, dudtjr913 commented on frontend/src/components/MultiFilterSelector.tsx
> +    data.map((value) => ({
한번 다시 도전해볼게요. 제가 이렇게 했던 이유는 모달의 특성때문이엿어요. 이것도 피알에 올리려고 했는데 깜빡했네요.

모달이 한번 열리게 되면 모달을 열었던 컴포넌트에서는 더이상 모달 상태를 변경할 수가 없게 되는데, 이것 때문에 예전에도 이슈가 한번 있었던 것으로 기억해요. 그래서 방법을 찾다가 모달을 여는 부모에게서 초기 상태만 가지고와서 자식의 지역상태로 관리하는 방법이였어요.(설명을 잘 못해서 이해하실지 모르겠네요..ㅠㅠ 왜이렇게 설명이 어렵지?!ㅋㅋㅋ)
즉, 부모가 상태를 모달에게 전달한 뒤 모달에서 부모의 상태를 업데이트해도 props는 변경되지 않기 때문에 초기 상태가 계속 유지돼요...

저도 위에서 한번에 내려주는게 더 좋다고 생각했고, 알고리즘도 따져가면서 최대한 구현을 열심히 해봤는데 최선이였어요ㅠ 부모로부터 물려주는 방식을 한번 생각해볼게요!

2021-09-03 06:42 UTC, dudtjr913 commented on frontend/src/components/MultiFilterSelector.tsx
> +  data: { id: number; name: string }[];
아 이 부분도 고민을 하던 부분이였는데 고민하다가 그냥 까먹어버린 것 같은데 딱 짚어주셨네요! 
이게 PublicSearchResultpage에서 똑같은 인터페이스를 받아서 써야되는데요.. PublicSearchResultPage에 존재하는 인터페이스를 export로 넘겨주자니 순환참조가 될 것 같고(MultiFilterSelector => PublicSearchResultPage => MultiFilterSelector ... 아닐 수도 있어요!), 각각 쓰자니 너무 유연하지 않은 것 같고.. 해서 여기 부분만 타입을 다른 파일에 모아서 관리해도 될지 의논해보고 싶었어요.

아니면 설계 자체가 잘못된걸까요? 지금까지 부모의 인터페이스를 바로 자식에게 그대로 물려줘야 했던 경우가 있었나.. 싶긴 해서요ㅠㅠ 얘기해보면 좋을 것 같아요.

2021-09-03 06:52 UTC, dudtjr913 commented
UX 개선 사항에 대해서도 얘기해보면 좋을 것 같아요. 고민이 조금 있었는데, 실시간으로 보여주는 것에 대한 이점은 어떤 필터링을 선택했을 때, 결과가 없다면 모달을 끄지 않고도 아 이렇게 필터링하니까 결과가 없구나. 이건 제거해야지! 할 수 있을 것 같고, 단점으로는 계속 api를 요청해야 하고, 필터를 했는데 뒤에 화면이 막 바껴서 혼란스러울 수도 있겠다? 정도가 생각나네뇨.

확인 버튼을 눌렀을 때 한번에 바꾸는 것에 대한 장점은 딱 실시간의 반대인 것 같아요. 확인 버튼을 눌렀을 때 변경하는 것이 더 좋을까요?

2021-09-03 07:14 UTC, GwangYeol-Im commented
> UX 개선 사항에 대해서도 얘기해보면 좋을 것 같아요. 고민이 조금 있었는데, 실시간으로 보여주는 것에 대한 이점은 어떤 필터링을 선택했을 때, 결과가 없다면 모달을 끄지 않고도 아 이렇게 필터링하니까 결과가 없구나. 이건 제거해야지! 할 수 있을 것 같고, 단점으로는 계속 api를 요청해야 하고, 필터를 했는데 뒤에 화면이 막 바껴서 혼란스러울 수도 있겠다? 정도가 생각나네요.
> 
> 확인 버튼을 눌렀을 때 한번에 바꾸는 것에 대한 장점은 딱 실시간의 반대인 것 같아요. 확인 버튼을 눌렀을 때 변경하는 것이 더 좋을까요?

서로의 장단점을 비교해보았을 때 변경 사항을 하나의 데이터를 선택할 때마다 적용하는 게 사용성이 더 좋아보이긴 하네요! 어색하게 느껴진 부분을 잠깐 고민해봤는데요, 모달이 켜지면서 Dimmed가 뜨게 되면 뭔가 뒤에 있는 화면은 비활성화 상태일 거라는 기대가 있어서 결과가 적용되는 게 이상해 보였다고 생각해요. (지극히 개인적인 의견) 그래서 선택을 할 때마다 모달을 닫아주든지, 혹은 Dimmed 없이 모달만 뜨게 하든지 하는 방법도 생각해볼 수 있을 것 같아요!

2021-09-03 07:17 UTC, dudtjr913 commented
혹시 아이디어스 어플 깔려있나요? 아이디어스에서 필터링을 하면 실시간으로 바뀌면서 딤드까지 있는데 어색하다는 느낌은 안들거든요! 혹시 확인 가능할까요? 아니면 저희 딤드가 너무 색이 진해서 어색할 수도 있겠네요!

2021-09-03 09:46 UTC, dudtjr913 commented
디스코드에서 말씀드린 대로 UI를 고쳐봤어요. 추가적으로 실시간으로 반영할 필요가 사라져서 카일이 말씀하신 대로 isSelected를 부모에서 생성하고, 모달에서는 받아서 쓰는것으로 해결할 수 있었어요. 모달은 실시간일 때가 문제인 것 같아요. 

multiFilter가 배열인데 multiFilter의 data도 배열이라서 로직이 엄청 더럽네요...ㅠ 계속 두 번씩 펼쳐줘야 하는 슬픔이 있어요.. 어떻게 잘 고칠 수 없을까요? 어쩔 수 없는걸까요? 카일의 도움이 필요합니다. 어쩌피 작성자, 태그 이외에는 필터링이 생기지 않을 것 같으니 multiFilter을 쓰지 말고 그냥 각각 상태로 들고 있을까요???

하나 더 고민인 것은 작성자, 태그 필터링을 하는 데이터를 언제 불러올지에 관한 것이에요. 처음 작성자와 태그를 눌렀을 때 데이터를 불러올지 아니면 검색 상세 페이지에 접근했을 때 바로 작성자, 태그를 불러올지 고민이에요. 바로 불러오는 것이 좋을 것 같긴 한데, 필터링을 굳이 누르지 않을 수도 있고, 바로 불러온다고 생각했을 때 데이터가 불러와진 상태가 아니라면 모달이 떴을 때 아무 데이터도 없는 것도 문제인 것 같아요. (여기에서도 모달은 props로 오픈될 때 한번만 받고 그대로 유지한다는 것 때문에 isLoading같은 것도 넘겨줄 수가 없네요😭😭) 그래서 만약 처음에 데이터를 불러오게 한다면 모든 데이터가 로드되었을 때 화면을 띄워줘야 할 것 같아요.(이럴 때 동시성 모드가 있으면 얼마나 좋을까요ㅠㅠ 버튼만 로딩하면 되는데..)

하지만 검색 결과를 불러오는 시간과 태그, 작성자를 불러오는 시간이 비슷하다면 괜찮을 것 같아요! 한번 기능 구현할 때 더 생각해볼게요. 카일의 의견은 어떤가요?

2021-09-03 11:57 UTC, GwangYeol-Im approved these changes
코드 좋네요 ㅎㅎ 뭔가 지금까지 상태를 수정하는 코드가 다 비슷하다보니 오히려 지금 방식으로 수정을 해주는 게 개인적으로 잘 읽히는 느낌입니다! UI 측면에서 하나 말하자면, 선택된 태그 버튼 오른쪽에 x 표시도 있으면 어떨까 싶네요! (데이터 fetching 답변 작성중..)

2021-09-03 11:57 UTC, GwangYeol-Im commented on frontend/src/components/MultiFilterSelector.tsx
> +  const [multiFilterItemData, setMultiFilterItemData] = useState(data);
`data`라는 말은 포괄적이기도 하지만 단, 복수를 나누기가 애매해서 (단수는 datum인데 한번도 안써봤네요.. ㅋㅋ) 네이밍이 골치아파지는 거 같아요. 차라리 단수는 multiFilter[Item/Keyword/Value]로 네이밍을 하면 타입명이나 배열 변수명을 더 명확히 지어줄 수 있지 않을까요? ㅎㅎ

2021-09-03 11:57 UTC, GwangYeol-Im commented on frontend/src/components/MultiFilterSelector.tsx
> +  const [multiFilterItemData, setMultiFilterItemData] = useState(data);
아 그리고 궁금한 게 있었는데 PublicSearchResultPage에서 `selectedMultiFiters`의 `selected`는 어떤 이유로 들어가게 되었나요??

2021-09-03 12:03 UTC, dudtjr913 commented on frontend/src/components/MultiFilterSelector.tsx
> +  const [multiFilterItemData, setMultiFilterItemData] = useState(data);
ㅋㅋㅋㅋ multiFilters가 이미 변수명으로 존재해서 대충 지었다가 까먹고 안고친거같네요..하핳 고칠게요!

2021-09-03 12:04 UTC, dudtjr913 commented on frontend/src/components/MultiFilterSelector.tsx
> +  const [multiFilterItemData, setMultiFilterItemData] = useState(data);
data도 처음에 쓰기 시작해서 계속 썼는데 쓰다보니까 이게 단수인지 복수인지 헷갈리긴 했어요.. 근데 고치려고 보니 너무 많고... 해서 냅뒀는데 고치겠습니다

2021-09-03 12:06 UTC, dudtjr913 commented on frontend/src/components/MultiFilterSelector.tsx
> +  const [multiFilterItemData, setMultiFilterItemData] = useState(data);
x버튼은 필요 없을 것 같아서 안넣었어요. x가 잇으면 x를 눌렀을 때 사라져야 할 것 같은데, 그렇게 되면 또 x버튼 아닌 부분은 눌렀을 때 어떻게 해야되고.. 이런 것들이 복잡해서요! 그리고 벨로그도 x표시 없이 누르면 삭제되는데 어색하다고 느낀 적이 없어서 괜찮다고 생각했어요!

그래도 넣는게 좋을까요?

2021-09-03 12:11 UTC, dudtjr913 commented
좋아용~

2021-09-03 14:53 UTC, dudtjr913 commented
data => values로 모두 변경했고, value는 단수(객체), values는 복수(배열)입니다.
또한, 초기 작성자, 태그 필터링에 대한 데이터를 검색 상세 페이지에 접속했을 때 요청하도록 변경했습니다.(지금은 더미데이터를 넣고 있음)
마지막으로 interface와 type을 filter.ts 파일로 분리했는데 어떤가요? 현재 두군데에서 쓰이고 있어서 분리해봤습니다. 타입이라 re-export도 필요하지 않을 것 같아 그대로 둔 상태입니다.

2021-09-05 02:24 UTC, GwangYeol-Im approved these changes
전반적으로 가독성을 신경 써줘서 읽기 편하네요 👏🏻 타입에 대한 부분은 동일한 의견을 말하려고 했는데 깜빡해버렸네요 ㅜㅜ 죄송해요.

저도 타입 레이어을 따로 두어 관리하는 게 좋아보입니다! 둘 다 처음 프로젝트를 시작했을 때는 타입에 익숙지 않아 타입이 여러 파일에 혼재 되어 있는 듯 한데 나중에 정리를 해보는 것도 괜찮은 거 같아요 :) UI PR인데도 거의 기능 하나를 끝낸 듯한 분량이네요.. ㅋㅋㅋ 정말 고생많았어요 디토! 이만 머지 가시죵

2021-09-05 04:15 UTC, merged