S06 - 검색 상세 페이지에서 작성자, 태그 순 필터링 검색 기능을 구현한다.
woowacourse-teams/2021-botobo pull request #460
Opened 2021-09-06 13:15 UTC by dudtjr913

closes #440 

## 작업 내용
- 검색 상세 페이지에서 작성자, 태그 순 필터링 검색 기능을 구현했습니다.
- 검색 상세 페이지에서 사용되는 상태들을 atom에 두었습니다. atom에 넣으면서 다른 문제집에 들어갔다 오거나, 메인으로 갔다가 뒤로가기로 돌아오는 경우 데이터가 캐시되어 있습니다. 캐시 목적으로 사용했습니다. 그래서 예상하건데, 검색 페이지에서 검색어를 입력해서 검색 상세 페이지에 들어오는 경우에는 해당 atom을 초기화해야합니다. 
그래서 atom을 쪼개지 않고 하나로 관리하려고 하다가 로직이 많이 복잡해졌네요..ㅠㅠ 더 좋은 방법이 있으면 알려주세요!(그냥 resetPublicSearchResultState 한번만 하고 끝내려고..) 아, 추가적으로 singleFilters는 굳이 atom으로 관리하지 않았어도 되는데, 일관성을 위해 두었습니다. singleFilters만 훅에 있으니까 일관성이 너무 없어보여서요. 
- 모달에서 라우팅 기능을 사용할 일이 있었어서 ModalProvider를 라우트 안에 두었습니다. 예전에 필요했어서 옮겨놨는데, 훅으로 로직을 모두 옮기면서 필요하지 않아졌네요.. 하지만 몇가지 실험을 해본 경과 ModalProvider이 라우터 안에 있어도 기능에는 전혀 차이가 없는 것 같아서 그냥 둬도 괜찮을 것 같습니다. 어떻게 생각하시나요? 위험한 경우가 있을까요?
- 필터링을 클릭해서 삭제하는 경우에도 요청을 다시 보내도록 구현했습니다. 필터링 할 때마다 스켈레톤을 보여주는 것보다는 작은 로딩바를 보여주는 것이 더 나을 것 같아서 로딩바로 구현을 했는데 어떤가요? 지금은 로딩이 필터링 바로 밑에 뜨는데, 중간으로 옮길까요?
- 뭐든 지적해주세요!
## 주의 사항
- file changed가 많네요.. 좀 나눴어야 했는데 죄송해요. 필터링 기능이긴 해서요ㅠㅠㅠ
- 초기화 버튼을 아래에 둬봤는데 어떤가요? 그리고 버튼 클릭하면 이동하도록 변경했습니다~
- 태그/작성자를 가져오다가 실패했을 때 고민이 있습니다. 현재 초기 로드시에만 태그/작성자를 받아오고 있는데, 사용자가 태그/작성자를 클릭했을 때 실패한 것이 아니라서 에러 메시지를 띄우기는 좀 그렇다고 생각해서 에러 메시지는 띄우지 않고 있는데요, 실패했다면 어떻게 하는 것이 좋을까요? 나중에 사용자가 태그/작성자 버튼을 클릭할 때 요청을 보내는 것이 나을까요?
- 태그/작성자를 따로 set하고 있는데요, 하나가 실패하더라도 하나는 성공하길 바라면서 각각 구현하게 되었습니다. 괜찮은가요?
- recoil의 atom을 사용해서 전역 변수로 관리하고 있는데, 다른 페이지에 갔다 와도 데이터가 유지된다는 것 때문에 좋다고 생각했습니다. atom으로 계속 할까요? 아니면 다른 페이지처럼 지역 변수로 관리할까요?
- 기본적으로 검색 결과가 없다면 돌아가기 버튼을 띄워줬었는데요, 실제로 검색하고 들어왔을 때 검색 결과가 없다면 돌아가기 버튼이 나오는 것은 좋다고 생각하는데, 필터링을 해서 검색 결과가 없을 때 돌아가기 버튼을 클릭하면 검색 페이지로 돌아가기 때문에 좋지 않다고 판단해서 제거했습니다.(필터링은 라우팅을 replace로 하고 있기 때문) 즉, 검색 결과가 실제로 없다면 돌아가기 버튼이 있지만, 검색 결과는 있었는데 필터링을 했을 때 결과가 없다면 메시지만 띄워주고 있습니다. 괜찮을까요?
- 필터링에 디바운스를 걸어야할까요? 현재는 필터링 시 계속 요청을 보내고 있는데, 그래서 엄청나게 빠르게 필터를 하거나 삭제하거나 한다면 살짝 밀리는 것이 보입니다. 하지만 디바운스를 걸자니 검색 속도가 중요하다고 생각하는데, 0.x초라도 줄이는 것이 맞지 않을까? 라는 생각이 들어서 걸지 않았습니다. 어떻게 생각하시나요? 디바운스를 걸어서 조금이라도 요청을 줄이자 vs 디바운스를 걸지 말고 지금처럼 유지하자(어쩌피 데이터도 별로 안밀린다)

질문 사항이 많네요.. 혼자 계속 고민하던 것들이였고, 더 많았는데 기억이 안나네요 ㅠㅠㅠ 기억나면 디스코드로 전송하겠습니다.

아 그리고 file changed가 많아서 죄송합니다. 다음부터는 최대한 잘라서 가져가겠습니다😭😭😭

2021-09-09 02:07 UTC, GwangYeol-Im requested changes
코드 잘 읽었습니다! 일단 코드 레벨에서 의견 드릴 수 있는 부분은 최대한 다 드릴 수 있도록 코멘트 남겼고 UI UX 관련 피드백은 주기적으로 요청 드리도록 하겠습니다 :) 질문은 모두 확인 했고 동의 + 별다른 코멘트를 남기지 않아도 되는 질문은 스킵했습니다!

> 필터링을 클릭해서 삭제하는 경우에도 요청을 다시 보내도록 구현했습니다. 필터링 할 때마다 스켈레톤을 보여주는 것보다는 작은 로딩바를 보여주는 것이 더 나을 것 같아서 로딩바로 구현을 했는데 어떤가요? 지금은 로딩이 필터링 바로 밑에 뜨는데, 중간으로 옮길까요?

현재 방식과 위치 모두 좋은 것 같습니다 ㅎㅎ 무한 스크롤이 구현되어 있을 텐데, 스크롤을 내려 새로 fetch를 받아올 때 아래쪽에만 로딩이 뜨지 않나요? 일관된 사용자 경험을 위해 그대로 두는 것에 동의해요~

> 초기화 버튼을 아래에 둬봤는데 어떤가요? 그리고 버튼 클릭하면 이동하도록 변경했습니다~

바라던 방향이라 만족합니다 👍🏻

> 태그/작성자를 가져오다가 실패했을 때 고민이 있습니다. 현재 초기 로드시에만 태그/작성자를 받아오고 있는데, 사용자가 태그/작성자를 클릭했을 때 실패한 것이 아니라서 에러 메시지를 띄우기는 좀 그렇다고 생각해서 에러 메시지는 띄우지 않고 있는데요, 실패했다면 어떻게 하는 것이 좋을까요? 나중에 사용자가 태그/작성자 버튼을 클릭할 때 요청을 보내는 것이 나을까요?

초기 페이지 단에서는 아무 처리를 안해주는 게 좋아 보입니다. 이 부분에 대해 개인적인 생각을 나눠보자면,

- 검색 결과 페이지에는 항상 문제집이 있다 -> 그에 맞는 태그나 작성자는 항상 있다.
- 바텀 모달 쪽에서 태그 or 작성자의 개수가 0이라면 적절히 받아오지 못한 것이라 가정
- 위의 경우 바텀 모달에 새로 고침 or 다시 시도하기 버튼을 보여줘 해당 버튼 클릭시 재요청

이렇게 가져가보면 어떨까 생각이 드네요..!

> recoil의 atom을 사용해서 전역 변수로 관리하고 있는데, 다른 페이지에 갔다 와도 데이터가 유지된다는 것 때문에 좋다고 생각했습니다. atom으로 계속 할까요? 아니면 다른 페이지처럼 지역 변수로 관리할까요?

저번에 이 부분에 대해 의논한 적이 있어 캐싱 방향을 유지하는 건 괜찮다고 생각합니다만, 디토도 언급해주셨듯 `singleFilters` 등 정말 recoil에서 관리해야하는 상태인지에 대해서 의문이 생길 수 있는 상태가 몇개 있는 것 같아요..! 일관성 측면이라면, 필터는 모두 페이지에 있고 멀티 필터에 관련된 데이터만 캐싱해서 멀티 필터에 맵핑해줄 수 있는 방법은 없을까요? 👀

> 필터링에 디바운스를 걸어야할까요? 현재는 필터링 시 계속 요청을 보내고 있는데, 그래서 엄청나게 빠르게 필터를 하거나 삭제하거나 한다면 살짝 밀리는 것이 보입니다. 하지만 디바운스를 걸자니 검색 속도가 중요하다고 생각하는데, 0.x초라도 줄이는 것이 맞지 않을까? 라는 생각이 들어서 걸지 않았습니다. 어떻게 생각하시나요? 디바운스를 걸어서 조금이라도 요청을 줄이자 vs 디바운스를 걸지 말고 지금처럼 유지하자(어쩌피 데이터도 별로 안밀린다)

저는 요새 이 부분에 대한 좀 더 근본적인 해결책이 있지 않을까 궁금해서 race condition handling이라는 키워드로 공부를 많이 해보고 있는데요, 실질적으로 중첩되는 요청 사이에 맨 마지막 요청에 대해서만 응답을 받을 수 있도록 하는 방법도 있을 거 같더라구요! 일단은 저도 속도를 위해 디바운스를 걸지 않는 게 괜찮다고 생각합니다. 이 부분은 기능 완료 후 추후 리팩토링 과제로 가져가도 괜찮을 것 같아요 :)

\+ 추가로 궁금한 사항이 있습니다! 실제 필터링이 이루어지나 확인해볼 수 있는 방법이 현재 메인의 문제집 -> 문제집 상세 -> 태그 검색을 이용해 검색 결과 페이지로 이동하는 방법이어서 그 단계를 거쳐 확인해봤는데, 아직 필터링이 되지는 않은 거 같더라구요. 이 부분은 api 를 붙인 뒤 확인해야하는 걸까요??

2021-09-09 02:26 UTC, dudtjr913 commented on frontend/src/api/index.ts
> +  getUsersWhenWorkbookSearchAsync,
좋네요! 감사합니다

2021-09-09 02:27 UTC, dudtjr913 commented on frontend/src/components/MultiFilterSelector.tsx
> +  name: MultiFilterNames;
맞아요!

2021-09-09 02:29 UTC, dudtjr913 commented on frontend/src/components/MultiFilterSelector.tsx
> +  query: UsePublicSearchQueryType;
그렇네요.. 아무 생각 없이 그냥 이름을 그대로 지어버렸어요 ㅋㅋㅋ 감사합니다.

2021-09-09 02:44 UTC, dudtjr913 commented on frontend/src/components/MultiFilterSelector.tsx
> +          });
좋아요~~!!

2021-09-09 02:50 UTC, dudtjr913 commented on frontend/src/components/PublicWorkbookList.tsx
> +        <li ref={scrollTarget} key={index}>
아, 이 부분을 설명하지 않았었네요! id로 두니까 빠르게 필터링을 했을 때 등록되어 있는 scrollTarget ref가 바뀐 li 태그를 보지 않고 이전 li 태그를 보고 있어서 요청을 두 번 보내는 현상이 발생했었습니다.

조금 더 자세하게는 이름 순으로 했을 땐 가장 마지막에 있는 Java0이 카드개수 순으로 하면 가장 위에 올라오는 것을 볼 수 있는데요. 빠르게 필터링을 하게 되면 화면이 빠르게 필터링 된 결과로 두번 따닥 바뀌는 현상을 볼 수 있어요. 리액트는 이 부분에서 element의 key가 같다고 판단해서 ref를 교체해주지 않는데요, 그래서 가장 밑에 있던 Java0이 가장 위에 올라오면서 바로 IntersectionObserver가 발동되어서 요청을 한번 더 보내고, 옵저버 연결도 끊어버리는 현상이 있었습니다.
그래서 해당 페이지는 get 요청 밖에 없다고 판단하여 데이터의 수정, 삭제가 불가능하기 때문에 key를 index로 줘도 된다고 판단했습니다.
![image](https://user-images.githubusercontent.com/64782636/132613972-28b904d8-ef3c-41f9-ad00-e5782c7a9cc6.png)
![image](https://user-images.githubusercontent.com/64782636/132613999-86bb6696-cf4c-4ca3-8a95-435b892077c2.png)

2021-09-09 02:55 UTC, dudtjr913 commented on frontend/src/components/PublicWorkbookList.tsx
> +        await searchForPublicWorkbook({ keyword, tags, users }, false);
이 부분은 저의 네이밍 센스가 잘못되었다고 생각되네요. isNew 보다는 isAdded? ... 흠 어렵네요. 설명을 해보겠습니다.
우선, prevValue.publicWorkbookResult로는 분기처리가 불가능할 것 같습니다. 제가 의도했던 바는 필터링을 하는 경우에는 이전 publicWorkbookResult가 있어도 날려버리고 새로운 데이터를 받기 위함이였고, 단순히 스크롤을 내려서 검색 요청을 하는 경우에는 새로 받아온 publicWorkbookResult과 이전 publicWorkbookResult을 합쳐주는 식으로 무한 스크롤을 구현했습니다.

즉, prevValue.publicWorkbookResult는 항상 존재하고, 필터링인지 스크롤인지 여부에 따라 데이터를 새롭게 추가할지 원래 있던 데이터에 추가해줄지를 결정하는 로직이였습니다. 

isNew라고 되어 있어서 헷갈릴 수 있다고 생각합니다. isFiltered정도로 바꾸면 괜찮을까요?

2021-09-09 03:05 UTC, dudtjr913 commented
피드백 감사합니다. 많았을텐데.. 고생하셨네요! 이해하기 힘들었을 것 같은데 피드백 남겨주신 것 보면 다 이해하신 것 같네요! 대단해요👍👍👍👍 피드백 모두 반영할 예정이고, 코멘트도 모두 달아놨습니다.추가적으로 모달을 열면 화면이 조금씩 아래로 밀리는 현상이 발생하는데, 이전에는 왜 못봤을까요ㅠㅠ 갑자기 그러는 것 같은데 이 부분도 고쳐서 다시 리뷰 요청 하겠습니다~

초기 페이지 단에서는 아무 처리를 안해주는 게 좋아 보입니다. 이 부분에 대해 개인적인 생각을 나눠보자면,

검색 결과 페이지에는 항상 문제집이 있다 -> 그에 맞는 태그나 작성자는 항상 있다.
바텀 모달 쪽에서 태그 or 작성자의 개수가 0이라면 적절히 받아오지 못한 것이라 가정
위의 경우 바텀 모달에 새로 고침 or 다시 시도하기 버튼을 보여줘 해당 버튼 클릭시 재요청
이렇게 가져가보면 어떨까 생각이 드네요..!

- 좋은 의견 감사합니다. 태그나 작성자의 검색 결과가 없을 때 어떤 처리를 해주는 것도 좋을 것 같네요. 이 부분은 생각하긴 했지만 어떤 식으로 요청을 보내야 할지 고민이였습니다. 카일이 말씀해주신대로 새로 고침이나 다시 시도하기 버튼을 두는 것이 개발자 입장에서는 좋을 것 같습니다. 하지만 사용자 입장에서는 태그나 작성자 모달을 열었을 때, 자신이 요청한 적도 없는데 새로 고침이나 다시 시도하기 버튼이 있고, 그 버튼을 눌러야만 데이터를 받아온다는 것이 어색할 수도 있다는 생각이 들었습니다. 
그래서 제가 생각했던 방법은 태그나 작성자 데이터가 없을 때, 태그나 작성자 버튼을 클릭하면 바로 요청을 보내는 것이었고, 이에 대해서는 어떻게 생각하시나요?

저번에 이 부분에 대해 의논한 적이 있어 캐싱 방향을 유지하는 건 괜찮다고 생각합니다만, 디토도 언급해주셨듯 singleFilters 등 정말 recoil에서 관리해야하는 상태인지에 대해서 의문이 생길 수 있는 상태가 몇개 있는 것 같아요..! 일관성 측면이라면, 필터는 모두 페이지에 있고 멀티 필터에 관련된 데이터만 캐싱해서 멀티 필터에 맵핑해줄 수 있는 방법은 없을까요? 👀
- 한번 그렇게 구현을 해보겠습니다. 도전!

저는 요새 이 부분에 대한 좀 더 근본적인 해결책이 있지 않을까 궁금해서 race condition handling이라는 키워드로 공부를 많이 해보고 있는데요, 실질적으로 중첩되는 요청 사이에 맨 마지막 요청에 대해서만 응답을 받을 수 있도록 하는 방법도 있을 거 같더라구요! 일단은 저도 속도를 위해 디바운스를 걸지 않는 게 괜찮다고 생각합니다. 이 부분은 기능 완료 후 추후 리팩토링 과제로 가져가도 괜찮을 것 같아요 :)
- `실질적으로 중첩되는 요청 사이에 맨 마지막 요청에 대해서만 응답을 받을 수 있도록 하는 방법`은 디바운스를 걸지 않고도 가능한 것인가요? 요청은 다 보내고, 그 중에서 마지막 요청만 받는 것이 가능한가요?!! 

+ 추가로 궁금한 사항이 있습니다! 실제 필터링이 이루어지나 확인해볼 수 있는 방법이 현재 메인의 문제집 -> 문제집 상세 -> 태그 검색을 이용해 검색 결과 페이지로 이동하는 방법이어서 그 단계를 거쳐 확인해봤는데, 아직 필터링이 되지는 않은 거 같더라구요. 이 부분은 api 를 붙인 뒤 확인해야하는 걸까요??
- 필터링 api가 나오지 않았습니당..ㅜ

2021-09-10 04:35 UTC, GwangYeol-Im commented on frontend/src/components/PublicWorkbookList.tsx
> +        <li ref={scrollTarget} key={index}>
아 intersection observer와 관련된 ref 문제가 있었군요..! 그런 이유라면 좋습니다 :)

2021-09-10 04:46 UTC, GwangYeol-Im commented on frontend/src/components/PublicWorkbookList.tsx
> +        await searchForPublicWorkbook({ keyword, tags, users }, false);
아 그런 의미였군요 ㅋㅋ 단순히 배열이 비어있을 때만 봐주는 게 아니라 확실히 플래그 변수 하나가 필요하겠네요! 이 메서드를 다른 데에서도 쓰는 것 같아 `isFiltered`는 제한적일 수 있을 것 같구, `isReset`은 어떻게 생각하시나요?? 제가 헷갈렸던 지점을 잠시 생각해봤는데, 들어오는 첫번째 인자 이름이 `newWorkbooks`인데, 그럼 항상 새로운 게 아닐까 하는 착오에서 발생한 것 같습니다 :) 변수 유지하는 것은 저도 찬성합니다!!

2021-09-10 05:19 UTC, GwangYeol-Im commented
> 자신이 요청한 적도 없는데 새로 고침이나 다시 시도하기 버튼이 있고, 그 버튼을 눌러야만 데이터를 받아온다는 것이 어색할 수도 있다는 생각이 들었습니다. 그래서 제가 생각했던 방법은 태그나 작성자 데이터가 없을 때, 태그나 작성자 버튼을 클릭하면 바로 요청을 보내는 것이었고, 이에 대해서는 어떻게 생각하시나요?

이 의견도 일리 있다고 생각합니다! 확실히 사용자 입장에서 들어가자마자 다시 불러오기 버튼이 보이면 당황스러울 수도 있겠네요..!

> multiFilters의 values은 리코일에서 관리하고, 실체는 페이지에 있어서 값이 변경될 때마다 페이지의 지역변수와 리코일을 둘 다 업데이트를 해야해서 좋은 방법인지 잘 모르겠어요. 그렇다고 multiFilters와 multiFilterValues를 분리한다면 굳이(?)라는 생각이 들기도 하구요.. 어떻게 하는게 좋을까요?

유지 보수 측면에서 오히려 단점이 부각 되었다면, 이 부분은 디토의 방식을 유지해도 괜찮다고 생각해요. 아무래도 직접 코드를 짜지는 않았다 보니 상태의 성격이 다소 어색하게 느껴져서 건넨 제안이었고 반드시 고칠 정도는 아니었습니다~ 구현까지 해서 코드로 보여주셔서 감사해요 👍🏻

> 실질적으로 중첩되는 요청 사이에 맨 마지막 요청에 대해서만 응답을 받을 수 있도록 하는 방법은 디바운스를 걸지 않고도 가능한 것인가요? 요청은 다 보내고, 그 중에서 마지막 요청만 받는 것이 가능한가요?!!

저도 사실 토스 기출 문제에서 인사이트를 얻어 간간이 찾아보고 있는 단계입니다 ㅜㅜ 일단 짐작이 가는 키워드는 [AbortController](https://developer.mozilla.org/ko/docs/Web/API/AbortController)에요. 디바운스가 단지 UX 상에서 api call을 보내는 빈도를 낮춰주는 역할이었다면, 이 API같은 경우 실제로 api 요청 '자체'를 취소시킬 수 있다고 하네요. 그래서 초기 요청에 대한 응답이 다음 요청 전까지 들어오지 않은 경우에 대해 처리가 가능한 것 같은데 저도 좀 더 공부해보겠습니다 !!

2021-09-10 18:23 UTC, dudtjr913 commented
유지 보수 측면에서 오히려 단점이 부각 되었다면, 이 부분은 디토의 방식을 유지해도 괜찮다고 생각해요. 아무래도 직접 코드를 짜지는 않았다 보니 상태의 성격이 다소 어색하게 느껴져서 건넨 제안이었고 반드시 고칠 정도는 아니었습니다~ 구현까지 해서 코드로 보여주셔서 감사해요 👍🏻
- 저도 고쳐볼 생각이 있어서 한번 고쳐봤습니다. 능력 부족인지는 모르겠지만 더 위험해보이는 코드가 된 것 같아서.. 다시 돌려놓겠습니다 ㅠ

Abortcontroller 키워드 감사합니다. 처음 들어보네요! 공부 해볼게요😍😍

2021-09-11 07:41 UTC, dudtjr913 commented
모오오오두 수정했습니다. 
추가적으로 처음 페이지에 진입했을 때, 작성자, 태그 요청 실패시 다시 요청을 보내도록 구현했습니다. 모달을 열면 다시 요청 보내고, 요청이 보내지는 동안 로딩바가 가운데서 돌고 있어요. 생각해보니 태그는 실제로 없을 수도 있을 것 같아서 로딩이 완료되었고, 결과가 없다면 결과가 없다는 텍스트도 보여주고 있습니다.

그리고 문제집 검색 결과가 없는 경우 버튼을 누를 수 없도록 구현을 했습니다!

2021-09-12 01:34 UTC, GwangYeol-Im commented
아주 좋네요 :) 사이드 이펙트에 대한 고려도 적절하다고 생각합니다 👍🏻 변경사항이 대체적으로 많지 않았어서 바로 머지를 해도 될 것 같네요! 충돌 나는 것만 해결해서 붙여주시면 될 것 같습니다 ㅎ.ㅎ 커밋 40개,, 정말 고생 많았어요 ☺️

2021-09-12 01:35 UTC, GwangYeol-Im approved these changes

2021-09-12 02:06 UTC, merged