S02 - 변경된 검색 API에 맞게 기능 구현한다.
woowacourse-teams/2021-botobo pull request #464
Opened 2021-09-09 07:49 UTC by ohjoohyung

closes #459 

## 작업 내용
- 변경된 검색 api에 맞게 수정했습니다 (tags, users 추가 및 order, type 삭제)
- 테스트도 추가 및 수정했습니다
- 솔직히 이미 검색을 피케이랑 중간곰이 specification과 criteria로 짱 완벽하게 구현을 해놔서 처음에는 이걸 굳이 QueryDSL로 바꿔야하나 싶었습니당..ㅠㅠ
- 그래도 사용해보니 처음 설정이 귀찮지 장점은 많더라고요
- 일단 적어도 어떤 기능을 새로 도입하면 그 이유는 반드시 있어야 한다는 생각이기에  QueryDSL을 도입하게 되면서 생긴 이점을 적어보자면 동적 쿼리를 메서드 체이닝을 이용해 훨씬 직관적으로 이해하기 쉽게 만들수 있다는 점이 있습니당! 그리고 컬럼명을 직접 string으로 적었던 것에 비해 QueryDSL을 사용하면서 만들어준 Q 클래스에 접근을 하여 필드를 사용하는 방식을 통해 컴파일 시점에서 에러 파악을 할 수 있다? 요런 장점이 있는거 같네요ㅋㅋㅋ
- 나중에 간단하게 위키에 정리해두겠슴다

## 주의 사항
- 없습니다! 그리고 하면서 이미 리졸버를 통해 파라미터를 만들어주는걸 워낙 잘 만들어놓으셨다보니 좀 편하게 구현했네요ㅋㅋ

2021-09-09 08:23 UTC, seovalue commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +    public Page<Workbook> searchAll(WorkbookSearchParameter parameter, List<Long> tags,
queryDSL 쓰면 Q도메인 필요한 줄 알았는데 없어도 상관이 없나보군요?!?! 싱긔

2021-09-09 08:24 UTC, seovalue commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepository.java
> +public interface WorkbookRepository extends JpaRepository<Workbook, Long>, JpaSpecificationExecutor<Workbook>, WorkbookRepositoryCustom {
사용하지 않는 findAll 메서드 제거하면 JpaSpecification도 extends 안해도 되지 않나요옹?

2021-09-09 08:26 UTC, seovalue commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +       QueryResults<Workbook> results =  jpaQueryFactory.selectFrom(workbook)
where로 조건 거는거 진짜 싕기하네용 먼가 criteria랑 비슷한데 코드 가독성이 더 좋은 느낌

2021-09-09 08:28 UTC, seovalue commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +import static botobo.core.domain.workbook.QWorkbook.workbook;
QWorkbook은 어떻게 하면 받아올 수 있나요? 코드 pull 했는데도 코드에 포함되어있지 않은데 저만 그런가요????

2021-09-09 08:30 UTC, seovalue commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +        if (searchKeyword == null || searchKeyword.equals("")) {
searchKeyword.equals("")를 하면 SearchKeyword 객체랑 "" 문자열이랑 같은지 비교하는 거인가요? 
뭔가 `searchKeyword.getValue().equals("")`이런식으로 해주는게 맞는 것 같아서요!

2021-09-09 08:32 UTC, seovalue commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +public class WorkbookRepositoryImpl implements WorkbookRepositoryCustom {
WorkbookRepositoryImpl도 테스트가 있으면 좋을 것 같아요!!

2021-09-09 08:33 UTC, seovalue requested changes
오랜만에 리뷰하니 신나서 equest Changes 한번 남겨봅니다! ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ ㅎㅎ
빠른 시간 안에 QueryDSL 적용하시느라 수고 많으셨어유!!!! 👍 👍  
몇가지 리뷰 남겼는데 확인 부탁드려용!!

2021-09-09 11:49 UTC, ohjoohyung commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepository.java
> +public interface WorkbookRepository extends JpaRepository<Workbook, Long>, JpaSpecificationExecutor<Workbook>, WorkbookRepositoryCustom {
와 대박..
바로 삭제

2021-09-09 11:50 UTC, ohjoohyung commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +       QueryResults<Workbook> results =  jpaQueryFactory.selectFrom(workbook)
그쵸?ㅋㅋㅋ 가독성은 짱 좋아졌습니다

2021-09-09 11:50 UTC, ohjoohyung commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +import static botobo.core.domain.workbook.QWorkbook.workbook;
아!! 빌드해주셔야 합니다!!!

2021-09-09 11:51 UTC, ohjoohyung commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +        if (searchKeyword == null || searchKeyword.equals("")) {
헉.. 문자열 비교 맞습니다.. 바로 수정!!

2021-09-09 11:51 UTC, ohjoohyung commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +public class WorkbookRepositoryImpl implements WorkbookRepositoryCustom {
오옷!! 좋네요!!
한번 만들어보겠습니당

2021-09-10 07:30 UTC, pkeugine approved these changes
ㅋㅋㅋㅋㅋㅋㅋㅋ
작업내용에 오즈가 의식의 흐름으로 내용을 적어주신 점이 인상깊었습니다.

Criteria -> QueryDSL 마이그레이션 해보는게 정말 좋은 경험이라고 생각해요!
컬럼명 스트링으로 적는 것이 확실히 불편했는데 코드를 보면서 이래서 QueryDSL을 쓰는구나, 이래서 오즈랑 협업하는구나 했습니다.

고생하셨습니다!! 생일 즐겁게 잘 보내세요 🎉💃🕺🎉💃🕺🎉💃🕺🎉💃🕺

2021-09-10 07:30 UTC, pkeugine commented on backend/src/docs/asciidoc/search.adoc
> +|검색어
오즈가 변경한 부분은 아닌데, 우리 문서를 만들 때 보면 `quizzes.adoc`이랑 `admin.adoc`에 각각 '퀴즈 생성 실패'와 '카드 생성 실패'가 더 이상 필요하지 않게 되었어요! (에러 코드 만들게 되면서 실패에 관한 문서는 따로 하지 않기로 해서)
해당 부분 문서화 테스트는 없는데 충돌 해결하면서 아직 adoc 부분은 남아있는 것 같네요.
오즈 pr 에서 지우고 머지하면 깔끔할 것 같습니다! 👍

2021-09-10 07:30 UTC, pkeugine commented on backend/src/test/java/botobo/core/domain/card/CardRepositoryTest.java
> +@Import(value = TestConfig.class)
오... JPAQueryFactory는 DataJpaTest가 넣어주지 않는구나

2021-09-10 07:30 UTC, pkeugine commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +                .in(tags);
Q클래스를 사용해서 쿼리를 만드는게 이런거구나 깔끔하네요!

2021-09-10 11:38 UTC, ggyool approved these changes
와 QueryDsl 을 사용하니 깔끔해지는군요 👍👍👍 괜히 Specification을 썼다는 생각이 드네요 ㅋㅋ
고생하셨습니다. 코드가 깔끔하네요~

리뷰를 위해 미루던 QueryDsl을 공부하게 됐네요. 감사합니다 ㅋㅋ
몇 시간 안 보고 의견을 남겨서 틀린 말이 있을 수 있는데 한 번 고민해 봐요!

### 아래 내용은 제가 흐름을 잘못 알고 있었네요.. 취소입니다😓
botobo.r-e.kr 에서 UI보고 알았습니다..
검색하면 태그랑 작성자를 들고와야 한다고 생각했는데, 아니었네요 지성 😓😓😓

현재 제가 이해하고 있는 흐름은 아래와 같은데요.
1. 유저가 java 라는 이름으로 검색을 한다.
2. java를 포함하고 있는 문제집을 가져온다. (/api/search/workbooks)
3. java를 포함하고 있는 문제집들의 태그를 가져옴 (/api/tags?workbook=java) 
4. java를 포함하고 있는 문제집들의 작성자를 가저옴 (/api/users?workbook=java)

2번의 결과로 3,4번 결과도 같이 주면 어떨까요 ??
현재 검색 API에서 List<Long> users와 List<Long> tags 를 받고 있는데.
리스트가 null 이면 2번 결과처럼 다 주면 되고.
리스트에 id 가 있으면 in 절 실행하고, 클라이언트에게 받은 리스트 그대로 넘겨주면 편하지 않을까? 하는 생각이 드네요.

2021-09-10 11:38 UTC, ggyool commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +public class WorkbookRepositoryImpl implements WorkbookRepositoryCustom {
SearchService 도 분리되어 있으니 현재 WorkbookRepositoryImpl 을 레파지터리 빈으로 등록해서 WorkbookSearchRepository 로 분리해도 좋을 것 같다는 생각이 들어요.
이유는 첨 QueryDsl 을 접하는 거라 구조가 새로웠는데, 코드에 비해 상속 구조가 복잡하다는 생각이 들었어요.
보셨을 수도 있는데, 아래 링크에서 4번에 해당하는 방법입니다 !
[조졸두님 블로그 링크](https://jojoldu.tistory.com/372)

2021-09-10 16:01 UTC, seovalue commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +       QueryResults<Workbook> results =  jpaQueryFactory.selectFrom(workbook)
이거 코멘트 보고 왜 서브쿼리가 안좋을까? 했는데 성능이슈였군뇨뇨

https://jojoldu.tistory.com/520

2021-09-11 13:28 UTC, ohjoohyung commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +       QueryResults<Workbook> results =  jpaQueryFactory.selectFrom(workbook)
맞습니다.. 정말 잘 짚어주셨습니다..
저도 난해한 쿼리문이 나가길래 띠용했는데 일단 workbook을 제대로 가져오고 그 외 연관관계 조회 쿼리는 batch size로 해결되어 괜찮겠지 싶었거든요!!
그래서 딱히 join 안해도 잘들고오는구나 싶었는데 중간곰이랑 조앤 코멘트 보고 서브쿼리를 없애보았습니다!
아직까지 데이터가 작아서 join을 사용함으로써 성능 상의 이점은 잘 모르겠지만 select문을 더 안쓰는것에는 분명한 이점이 있을듯합니다!! 덤으로 n:1 관계인 user는 fetch join을 사용함으로써 user select문이 나가는걸 더 줄이게 되었습니다! 요거를 생각 못했었네용

2021-09-11 13:30 UTC, ohjoohyung commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +                .isNotEmpty();
잘 적용한건지는 모르겠지만 card랑 innerjoin을 함으로써 요걸 쓸 필요가 없어졌습니다!!

2021-09-11 17:11 UTC, ohjoohyung commented on backend/src/main/java/botobo/core/domain/workbook/WorkbookRepositoryImpl.java
> +public class WorkbookRepositoryImpl implements WorkbookRepositoryCustom {
와... 이런건 전혀 몰랐네용..
WorkbookSearchRepository라고 이름 바꾸고 @Repository 명시해서 빈으로 등록시켰습니다!!
글고 DataJpaTest는 @Repository를 안가져오는지 몰랐네요.. 그래서 안쓰는곳 @import 다 삭제했슴다
TestConfig의 경우 test에서 @TestConfiguration을 사용해야되는건가 생각했는데 그게 아니였네용..
그냥 QuerydslConfig를 사용해도 동일하게 작동해서 TestConfig는 삭제했습니다!!

2021-09-12 02:27 UTC, seovalue approved these changes
변경사항 확인했어요 👍🏻 고생했습니당

2021-09-12 02:27 UTC, seovalue commented on backend/src/test/java/botobo/core/domain/workbook/WorkbookSearchRepositoryTest.java
> +class WorkbookSearchRepositoryTest {
👍🏻👍🏻

2021-09-12 03:48 UTC, pkeugine approved these changes
바뀐 점 확인했습니다.
간단한 리뷰 두 개 남겨서 그것만 쓱 보시면 될 것 같네요.
고생하셨어요 오즈!!! 💃🕺💃🕺💃🕺

2021-09-12 03:48 UTC, pkeugine commented on backend/src/test/java/botobo/core/domain/workbook/WorkbookSearchRepositoryTest.java
> +class WorkbookSearchRepositoryTest {
👍👍

2021-09-12 03:48 UTC, pkeugine commented on backend/src/test/java/botobo/core/domain/workbook/WorkbookSearchRepositoryTest.java
> +                .allMatch(name -> name.contains("Java"))).isTrue();
```suggestion
        assertThat(workbookList).extracting(Workbook::getName)
                .allMatch(name -> name.contains("Java"));
```
저번에 중간곰도 조앤 리뷰에 남겨줬는데 이렇게 extracting 을 활용해서 테스트를 더 깔끔하게 만들 수 있을 것 같아요! 아 그리고 isTrue 없이도 테스트가 잘 돌아가더라구요 😁

만약 extracting으로 바꾼다면 이 테스트 클래스 전체적으로 변경이 필요하네요.

2021-09-12 03:48 UTC, pkeugine commented on backend/src/test/java/botobo/core/domain/workbook/WorkbookSearchRepositoryTest.java
> +        assertThat(workbookList).hasSize(0);
```suggestion
        assertThat(workbookList).isEmpty();
```
isEmpty()로 바꿔도 괜찮을 것 같네요 😁 

SonarQube 나 SonarLint 에서도 잡아주는데, 그 이유가
1. 특정 상황을 위해 제공하는 메서드가 있다면 그것을 활용하자
2. 에러 메시지가 그 상황에 더 어울리게 나온다

라고 합니다. 물론 둘 다 돌려서 에러 메시지 확인해보니까 hasSize를 써도 충분히 이해할 메시지가 나오긴 하더라구요.
그래도 1번 이유로 isEmpty()를 사용하기 적절해 보입니다 😄

2021-09-12 04:05 UTC, ggyool approved these changes
변경사항 확인했습니다! 새로운 거 하신다고 고생하셨습니다👍👍👍

2021-09-12 06:48 UTC, ohjoohyung commented on backend/src/test/java/botobo/core/domain/workbook/WorkbookSearchRepositoryTest.java
> +                .allMatch(name -> name.contains("Java"))).isTrue();
오오오!! 테스트에 대한 피드백이 필요했었는데 감삼다~~!! 전체적으로 extratcting을 사용하도록 수정했습니다!!

2021-09-12 06:48 UTC, ohjoohyung commented on backend/src/test/java/botobo/core/domain/workbook/WorkbookSearchRepositoryTest.java
> +        assertThat(workbookList).hasSize(0);
아하...!! 좋은 정보 감삼다ㅋㅋㅋ 수정했습니다!!!

2021-09-12 07:03 UTC, merged