P05 - 공유 문제집에 태그, 좋아요를 보여준다
woowacourse-teams/2021-botobo pull request #499
Opened 2021-09-13 13:01 UTC by GwangYeol-Im

closes #483 

## 작업 내용

## 주의 사항
UI 지적 달게 받겠습니다,,

2021-09-14 03:31 UTC, dudtjr913 requested changes
코드 잘 봤습니다! 
디자인이 살짝 수정되면 좋을 것 같다고 생각하는데 어떻게 생각하시나요?
![image](https://user-images.githubusercontent.com/64782636/133190216-c85636c8-c5c5-4d4e-9713-8ced0ff0e0bc.png)

지금은 너무 카드가 큰 것 같아서, 태블릿 사이즈부터는 2개를 보여줘도 될 것 같아요.
그러면서 제목, 태그같은 경우에는 2줄로 되거나 하트를 지나가는 현상이 발생하는데, 하트 자체를 absolute로 주는 것보다는 flex로 조절하는 것이 더 좋아보여요. 2줄로 되면 카드의 크기가 달라지기 때문에 ...으로 하는 것도 좋을 것 같구요!

태그도 마찬가지로 저번에 1줄을 넘어가면 ...으로 한다고 했던 것 같아서 맞춰주시면 좋을 것 같아요. 

아래는 문제의 화면입니다.

![image](https://user-images.githubusercontent.com/64782636/133190583-7760e518-0231-4c93-b517-7034dbd867cb.png)

2021-09-14 03:31 UTC, dudtjr913 commented on frontend/src/components/PublicWorkbook.tsx
> +        <li key={id}>#{name}</li>
#과 name 사이를 margin-right: 0.1rem으로 띄워주는게 좋을 것 같아요. 상세 페이지에서의 태그도 그렇게 되어 있어서 통일성을 위해서요!

2021-09-14 06:57 UTC, GwangYeol-Im commented on frontend/src/components/PublicWorkbook.tsx
> +        <li key={id}>#{name}</li>
원래 그렇게 하다가 글씨 크기가 작아지면서 넓어보여 삭제 했는데, 역시 넣는 게 낫겠군요! 감사합니당

2021-09-14 07:50 UTC, GwangYeol-Im commented
- 템플릿인 경우 고려해서 반응형 추가 했습니다.
- 문제집 이름이 15글자를 넘어갈 경우 display 길이를 15자로 맞춰주었더니 하트 간격에 영향이 가지 않아 구조는 바꾸지 않았습니다.
- 스켈레톤의 레이아웃도 카드 디자인에 맞게 변경 했습니다.
- 태그는 대표 태그 하나만 보여주고 나머지는 안에 들어가서 확인하는 게 좋다고 생각해 그대로 구현해봤는데, 이 부분에 대한 디토의 의견을 들어보고 싶어요!

2021-09-14 09:40 UTC, dudtjr913 requested changes
추가적으로 피드백 드렸습니다. 태그를 1개만 보여준다는 것에 대한 저의 생각은.. 어쩌피 한 줄을 차지하고 있기 때문에 한 줄까지는 다 보여줘도 된다고 생각합니다. 이 부분은 백엔드와도 얘기를 해보는 것이 좋을 것 같아요.

그리고 스켈레톤 반응형까지 구현해주신 것 짱이에요! 한가지 추가되면 좋겠다고 생각하는 것은 현재 스켈레톤이 반응형으로 2개씩 나올 때, 8개밖에 없어서 스크롤이 안생기는데 충분히 스크롤이 생길 만큼 넣어줘도 된다고 생각합니다. 그래서 한 12개로 늘리는건 어떨까요? 의견이 듣고싶네요!

2021-09-14 09:40 UTC, dudtjr913 commented on frontend/src/utils/format.tsx
> +export const formatWorkbookName = (name: string) =>
헉... 제 생각에는 이걸 만들 필요는 없었을 것 같아요... 충분히 css로 가능하다면 js보단 css가 성능에 더 좋다고 알고 있어서요! 성능이라는 키워드를 막 꺼내면 안되지만... 그래도 100개 이상의 데이터가 있을 수도 있는데, 모두 비교를 한다면 그만큼 비용이 발생할 것 같아요. 

그리고 제 생각은 저희가 모든 width를 고려할 수 없기 때문에 flex로 하트와 제목 간의 width를 비율로 정해줘야 한다고 생각해요. 그래서 width가 넘치면 ...으로 처리하는게 좋지 않을까요? 현재도 이렇게 많이 깨지는 핸드폰이 존재합니다!
![image](https://user-images.githubusercontent.com/64782636/133233648-f825e2a0-83ff-4ff9-b971-6a0b3412eb81.png)

css 키워드는 아실 것 같지만 text-overflow: ellipsis;과 overflow, white-space로 처리하면 될 것 같습니다. https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

2021-09-14 12:48 UTC, GwangYeol-Im commented
> 태그를 1개만 보여준다는 것에 대한 저의 생각은.. 어쩌피 한 줄을 차지하고 있기 때문에 한 줄까지는 다 보여줘도 된다고 생각합니다. 이 부분은 백엔드와도 얘기를 해보는 것이 좋을 것 같아요.

넵 ㅎㅎ 이 부분은 백엔드의 입장도 들어보고 결정하도록 하겠습니다! 의견 고마워요 👍🏻

> 한가지 추가되면 좋겠다고 생각하는 것은 현재 스켈레톤이 반응형으로 2개씩 나올 때, 8개밖에 없어서 스크롤이 안생기는데 충분히 스크롤이 생길 만큼 넣어줘도 된다고 생각합니다.

바로 적용하겠습니다~!~!

2021-09-14 12:51 UTC, GwangYeol-Im commented on frontend/src/utils/format.tsx
> +export const formatWorkbookName = (name: string) =>
이 부분은 저의 판단 미스였네요 🥲 크로스 브라우징을 이슈를 충분히 고려하지 않고 섣불리 판단했습니다. 최대한 빠르게 적용토록 할게요! 그리고 ...을 css로도 처리해줄 수 있는 방법이 존재했군요 ㅎㅎ 좋은 방법 공유해줘서 고마워요 :)

2021-09-15 18:27 UTC, dudtjr913 requested changes
마지막으로 수정하면 될 것 같아요. rem으로 width를 고정하는 것보다 %로 주는 방법이 좋아보여요. 카일 힘들게 하기 싫어서 혼자 구현해봤는데, 쉽지 않네요. 내일 같이 고민해봐요!

그리고 PublicSearchResultPage에서도 스켈레톤 12개로 늘려주셔도 좋을 것 같아요!

2021-09-15 18:27 UTC, dudtjr913 commented on frontend/src/components/PublicWorkbook.tsx
> +  width: 12.5rem;
아래에 리뷰를 달았는데, 이런건 %로 주는게 좋은 것 같아요. 모든 기기에서 대응하려면요!

2021-09-15 18:27 UTC, dudtjr913 commented on frontend/src/components/PublicWorkbook.tsx
> +  width: 15rem;
폴드에서는 15rem이 커서 깨지는데 %로 주고 싶어요.. 1시간 넘게 혼자 해봤는데 도저히 안되네요....ㅠㅠ
내일 같이 고민해볼까요?
%로 주면 컨텐츠릐 크기에 따라 flex의 width도 넓어져서 어떻게 할 방법이 없네요... 하아
![image](https://user-images.githubusercontent.com/64782636/133488330-691213f1-ccd8-411b-920d-37e680cc0091.png)

2021-09-16 01:41 UTC, GwangYeol-Im commented on frontend/src/components/PublicWorkbook.tsx
> +  width: 15rem;
ㅋㅋㅋㅋㅋ 저도 그래서 고정값 준거였어요 ㅠㅠ 사실 폴드도 확인을 했는데 저번에 디토랑 같이 개발하면서 폴드는 고려를 안하겠다? 는 흐름으로 갔던 기억이 있어서 나머지 기기에 정상적으로 보일 수 있도록 rem을 준 거였거든요,, ㅎㅎ 같이 얘기해보는 거 좋습니당

2021-09-16 01:46 UTC, GwangYeol-Im commented
> 그리고 PublicSearchResultPage에서도 스켈레톤 12개로 늘려주셔도 좋을 것 같아요!

제가 정신을 잠깐 놨었네요.. ^^ 적용했는데 왜그러지? 하고 봤더니 필터가 12개... 하하하 고치겠습니다.

2021-09-16 03:07 UTC, dudtjr913 commented on frontend/src/components/PublicWorkbook.tsx
> +  width: 15rem;
![image](https://user-images.githubusercontent.com/64782636/133542796-454656e1-d473-4faf-94d1-e515e6d5e581.png)
![image](https://user-images.githubusercontent.com/64782636/133542811-3f611de1-064f-483e-b790-0c3e8e54426f.png)
![image](https://user-images.githubusercontent.com/64782636/133542851-d1124eeb-4ae4-4cde-941c-bf454425e377.png)

얘기했던 것처럼 minmax를 사용해서 grid의 크기를 고정시켜주면 될 것 같아요!
아래 div는 width를 고정시켜줘야하고, 그 아래 h2는 width를 100%으로 설정도 해줘야합니다. 귀찮은것..
태그도 width 바꿔주세요!!

아 그리고, 공유 문제집 상세 페이지에 제목도 ...으로 표현되게 바꿔주시면 감사하겠습니다!

2021-09-16 04:50 UTC, merged