R01 - S3를 환경에 따라 분리하며, 로컬에서는 Fake 객체를 사용한다.
woowacourse-teams/2021-botobo pull request #532
Opened 2021-09-18 13:54 UTC by seovalue

closes #520 

## 작업 내용
* 기존 S3Uploader는 local에서는 동작하지 않는 무용지물이었습니다.
* 어차피 에러를 발생할 거, FakeS3Uploader를 만들어 local에서는 요청이 들어올 시 기존의 이미지를 응답하는 방식으로 일단 **동작**하게만 구성해두었습니다.
  * 원래는 resources/images에 저장하여, 해당 파일을 file 프로토콜을 이용해 전달할 생각이었으나 브라우저 보안 상 안된다고 하네요 ㅠ_ㅠ 그래서 일단은 동작만 하게 냅뒀는데, 혹시 다른 방법 생각나시는 게 있으시다면 언제든 코멘트 남겨주세요!
* 그리고 dev1-2, prod1-2에는 기존의 S3Uploader가 동작하도록 구성해두었습니다.
* s3 storage도 dev, prod 분리 진행했습니다. 기존 데이터는 storage에 저장되어있는데, storage-dev, storage-prod를 만들어 우선은 기존 데이터를 복사해두었습니다. 현재 main이 storage를 이용하고 있기 때문에 기존 버킷 삭제는 main에 해당 PR이 포함된 커밋이 머지된다면 그 때 진행하겠습니다.
*  요약하자면.. 기존 테스트에는 전혀 변화없이 로컬에서 FakeS3Uploader만 끼워넣는 식의 작업입니다.

## 주의 사항
* 에러 코드를 추가해서, [해당 파일](https://github.com/woowacourse-teams/2021-botobo/blob/1be2c6c7628681c21a17b1f8cdc278f533b4de7d/backend/src/docs/asciidoc/errors.adoc)을 @GwangYeol-Im  @dudtjr913 도 확인해주시면 좋을 것 같습니다.

2021-09-21 16:40 UTC, ggyool reviewed
안녕하세요 조앤! dev와 prod의 S3 버킷이 분리되었군요!
잘 만들어 주시느라 고생하셨네요👏👏👏

꽤 많은 리뷰를 남기게 되었는데요.
제가 잘못 파악하고 남긴 부분도 있을거라 생각해요 댓글로 알려주세요😉
편하게 의견 나눠봐요!

2021-09-21 16:40 UTC, ggyool commented on backend/src/main/java/botobo/core/config/S3DevConfig.java
> +@Profile({"dev1","dev2"})
인스턴스가 늘어나면 이 부분도 바꿔줘야 하니 @Profile("dev*") 같이 와일드카드를 지원해 주면 좋을 텐데, 안 되는 것 같더라고요.
좋은 방법이 없을까요?😓

2021-09-21 16:40 UTC, ggyool commented on backend/src/main/java/botobo/core/exception/common/ErrorType.java
> +    X001("X001", "정의되지 않은 에러", UndefinedException.class),
,찍고 ; 넣으면 되는군요 신기하네요 ㅋㅋ

2021-09-21 16:40 UTC, ggyool commented on backend/src/main/java/botobo/core/infrastructure/s3/FakeS3Uploader.java
> +@Component
```suggestion
@Profile({"local", "test"})
@Component
```
사용하지 않는 코드는 지워줘도 될 것 같습니다!

2021-09-21 16:40 UTC, ggyool commented on backend/src/main/java/botobo/core/infrastructure/s3/FakeS3Uploader.java
> +        return user.getProfileUrl();
```원래는 resources/images에 저장하여, 해당 파일을 file 프로토콜을 이용해 전달할 생각이었으나 브라우저 보안 상 안된다고 하네요 ㅠ_ㅠ 그래서 일단은 동작만 하게 냅뒀는데, 혹시 다른 방법 생각나시는 게 있으시다면 언제든 코멘트 남겨주세요!```

파일 프로토콜을 이용해 전달한 다는 게 어떤 건지 잘 모르겠네요😓
제가 상황을 이해한 바로는 resources/static 경로에 이미지를 저장해두고 url을 return 해주면 될 것 같습니다.
```suggestion
        // multipart 파일을 file로 변환 후 저장하는 로직
        return "http://localhost:8080/image.png";
```

개인적인 의견으로는 로컬 환경에서는 dev나 prod 처럼 동작하지 않아도 상관없다고 생각해요.
default-image 하나 두고 쓰는 것도 괜찮아 보입니다.
```suggestion
        return "http://localhost:8080/default-image.png";
```

2021-09-21 16:40 UTC, ggyool commented on backend/src/main/java/botobo/core/infrastructure/s3/S3Uploader.java
> +@Profile({"dev1", "dev2", "prod1", "prod2"})
```suggestion
@Profile("!test & !local")
```
나중에 인스턴스가 추가돼도 수정하지 않아도 되게끔 바꿔주면 좋을 것 같아요.
아직 merge 되지 않은 제 PR에서 이렇게 적용했는데 dev나 prod에서 테스트는 못해봤지만, 아마 문제없을 거라 생각해요.

2021-09-21 16:40 UTC, ggyool commented on backend/src/main/java/botobo/core/infrastructure/s3/S3Uploader.java
> -                makeUploadImageFile(multipartFile),
File 형태로 convert 하지 않아도 되는 거였군요~!
굳입니다👍👍

2021-09-21 16:40 UTC, ggyool commented on backend/src/main/java/botobo/core/infrastructure/s3/S3Uploader.java
> +        metadata.setContentType(String.valueOf(MediaType.ANY_IMAGE_TYPE));
제 인텔리제이에서는 아래 경고가 뜨는데 무시해도 되는 건지 궁금합니다!
'ANY_IMAGE_TYPE' is declared in unstable class 'com.google.common.net.MediaType' marked with @Beta

2021-09-21 16:40 UTC, ggyool commented on backend/src/main/java/botobo/core/infrastructure/s3/S3Uploader.java
> +        metadata.setCacheControl("max-age=31536000");
이건 이번 PR은 아닌데 잘 몰라서 질문드려요.
해당 옵션을 넣으면 1년 동안 S3에 남아있는 건가요?
1년 뒤에는 저절로 삭제가 되나요? 굼금함니다.

2021-09-21 16:40 UTC, ggyool commented on backend/src/main/resources/application.yml
> -spring:
여기가 지워져서 로컬에서 잘 실행되지 않더라고요. 의도하신 걸까요?

2021-09-21 16:40 UTC, ggyool commented on backend/src/main/resources/application.yml
>  logging:
이 옵션은 local에서만 필요한 걸까요? 그렇다면 application-local로 옮겨도 좋을 것 같습니다.
가끔씩 뜨는 ```com.amazonaws.SdkClientException: Failed to connect to service endpoint``` 에러 땜시 있는 것 같은데
넣었는데도 가끔씩 뜨더라고요.. 해결할 방법이 없을까요? 🤔

2021-09-21 16:40 UTC, ggyool commented on backend/src/main/resources/application.yml
> +    auto: false
반드시 있어야 하나요? 없어도 로컬에서 잘 돌아가는 것 같아서 질문드려요.
로컬에서는 Fake 를 쓰니까 불필요하지 않을까 생각하거든요.
이 셋팅도 로컬에서만 필요하면 application-local로 옮기면 좋을 것 같습니다!

2021-09-21 16:40 UTC, ggyool commented on backend/src/test/java/botobo/core/infrastructure/S3UploaderTest.java
>      void setUp() {
해당 테스트 클래스가 @Disabled 인 이유를 다시 한번 알려주실 수 있나요?
저번에는 제가 S3 업로드 + 태스트 대한 이해가 부족하여 상황 파악을 제대로 하지 못했네요 😭
간단하게만 적어주심 감사하겠습니다🙇‍♂️

2021-09-21 19:24 UTC, pkeugine commented on backend/src/main/java/botobo/core/config/S3DevConfig.java
> +@Profile({"dev1","dev2"})
프로필을 분리시킨건 제가 했는데, 다시 하나로 통합시킬 예정이라 고민하지 않아도 될 것 같아요!

2021-09-22 02:22 UTC, seovalue commented on backend/build.gradle
> -    from '../dev/aws-s3.yml'
이건 PR 코멘트에도 남겼는데요..! 아직 main이 aws-s3를 사용하고 있어서 지우는데 위험이 있어 메인까지 배포된 후에 지울 예정입니다

2021-09-22 02:24 UTC, seovalue commented on backend/src/main/java/botobo/core/infrastructure/s3/FakeS3Uploader.java
> +        return user.getProfileUrl();
오 static에 담으면 저렇게 반환되나요??!!?!!! 디폴트이미지 하나두고 반환하는거 좋은 것같아요 !! file:// 쓰니깐 ㅇ보안이슈로 안되더라구여 ㅠㅠ

2021-09-22 02:25 UTC, seovalue commented on backend/src/main/java/botobo/core/infrastructure/s3/S3Uploader.java
> +@Profile({"dev1", "dev2", "prod1", "prod2"})
suggested change안에 적힌게 안보여요.. ㅠㅠ

2021-09-22 02:26 UTC, seovalue commented on backend/src/main/java/botobo/core/infrastructure/s3/S3Uploader.java
> +        metadata.setContentType(String.valueOf(MediaType.ANY_IMAGE_TYPE));
저도 이거 궁금해서 냅뒀어요! ㅋㅋ jpeg, png에 따라서 타입을 다르게 넘겨줘야하는데 ANY가 있길래 우선 적용해보고 dev환경에서 잘 안되면 fix하려고 생각중입니다 ㅎㅎ 투두도 표시해둘게요

2021-09-22 02:26 UTC, seovalue commented on backend/src/main/java/botobo/core/infrastructure/s3/S3Uploader.java
> +        metadata.setCacheControl("max-age=31536000");
s3 옵션 아니고 브라우저에서 캐싱할 때 사용되는 옵션입니다~

2021-09-22 02:28 UTC, seovalue commented on backend/src/main/resources/application.yml
> -spring:
아 저는 항상 실행시킬 때 인텔리에서 edit configuration에서 환경을 설정해주고 실행해서 필요없다고 생각했어요. 다른분들도 그냥 실행한다면 추가해도 괜찮을듯?

2021-09-22 02:30 UTC, seovalue commented on backend/src/main/resources/application.yml
>  logging:
로컬 뿐만아니라 데브, 운영 모두 필요한 설정입니다. Failed to connect to service endpoint는 저 설정과 다른 에러인데 .••• 인스턴스에서 실행했을 때 뜨던가요?

2021-09-22 02:30 UTC, seovalue commented on backend/src/main/resources/application.yml
> +    auto: false
로컬에 없어도 돌아가던가요??? 제건 안돌아가서 추가해둔거라서 다시 확인해보겠슴다

2021-09-22 02:32 UTC, seovalue commented on backend/src/test/java/botobo/core/infrastructure/S3UploaderTest.java
>      void setUp() {
이 테스트가 돌아가려면 도커를 띄워야하는데,
1. 도커가 깔려있지 않은 경우
2. 도커에서 s3 이미지 가져온뒤 테스트함 -> 매우느림

이 두가지 경우로 우선 테스트할때만 돌려보고, 젠킨스 빌드할 땐 안돌리려구 @disabled 사용했어용

2021-09-22 08:27 UTC, ggyool commented on backend/build.gradle
> -    from '../dev/aws-s3.yml'
음.. 현재 main과 develop가 aws-s3.yml 파일을 사용하고는 있지만, remote의 aws-s3.yml 을 지워도 머지 되기 전까지는 이전 머지 된 커밋을 참조하고 있기 때문에 지워도 괜찮다고 생각했습니다.

처음 서브모듈을 도입했을 때 젠킨스에서 그렇게 설정 해두었던 것 같은데, 너무 예전일이라 지금은 어떻게 동작하고 있는지 모르겠네요.

정리를 하면 prod나 dev에서 remote 서브모듈을 참조하여 jar를 만든다면 지우면 안 되고, 아니라면 지워도 되는 상황이라 추측합니다.

2021-09-22 08:27 UTC, ggyool commented on backend/src/main/java/botobo/core/config/S3DevConfig.java
> +@Profile({"dev1","dev2"})
아 그렇군요! 알겠습니다

2021-09-22 08:31 UTC, ggyool commented on backend/src/main/java/botobo/core/infrastructure/s3/S3Uploader.java
> +@Profile({"dev1", "dev2", "prod1", "prod2"})
피시에서는 보이는데.. 아까 슬랙에서 눌러서 살짝 봣을 때는 안 보이더라고요? 😓
```@Profile("!test & !local")```
이런 내용이었는데요
피케이가 dev1,2와 prod1,2를 하나도 통합한다고 하니 나중에 "dev", "prod" 로 바꾸면 돼서 그대로 두셔도 좋을 겉 같아요.

2021-09-22 08:34 UTC, ggyool commented on backend/src/main/java/botobo/core/infrastructure/s3/S3Uploader.java
> +        metadata.setCacheControl("max-age=31536000");
아하.. 이미지 upload 시점에 적용되는 게 아니라 클라이언트에서 S3에 해당 이미지를요청했을 때 헤더에 붙여지는 건가 보군요! 감사합니다.

2021-09-22 08:46 UTC, ggyool commented on backend/src/main/resources/application.yml
> -spring:
인텔리제이에서 실행하지 않을 수도 있으니(프론트엔드 분들) 넣어두면 좋을 것 같습니다!

2021-09-22 08:49 UTC, ggyool commented on backend/src/main/resources/application.yml
>  logging:
모두 필요하군요 👍 

저걸로 시작하는 에러가 떠서 구글링 살짝 해봤었는데, 저 옵션을 추가하라는 글을 몇 개 봤어서 위처럼 생각했어요.
인스턴스에서는 테스트 못해보고 로컬에서는 뜨다 말다 하더라고요.

2021-09-22 08:56 UTC, ggyool commented on backend/src/main/resources/application.yml
> +    auto: false
아.. 죄송합니다. 넣어야 하네요🙏
로컬이랑 테스트 환경에서 AWS 관련 빈 등록을 하지 않을 방법이 없을까 찾아보다가 이런 걸 보고 넣어봤는데
이것 땜에 에러가 안 나던 거였습니다 !
로컬이랑 테스트에서 빈 등록 하지 않을 방법은 결국 못 찾았었네요..😓
```
@Profile({"test", "local"})
@EnableAutoConfiguration(
        exclude = {MessagingAutoConfiguration.class,
                ContextStackAutoConfiguration.class,
                ContextRegionProviderAutoConfiguration.class
        }
)
```

2021-09-22 12:00 UTC, seovalue commented on backend/build.gradle
> -    from '../dev/aws-s3.yml'
넵! 지금은 젠킨스 빌드할때마다 새로운 서브모듈 땡겨오도록 설정되어있어요!!!! 제 걱정은 혹시나 누군가 main에서 hotfix를 하게될 수도 있고.. 그때 문제가 발생할까봐 메인에 머지될때까지는 우선 냅두려고 생각하는 거에요! 공존 상태여도 사실 문제가 발생하진 않고요. 
혹시 급하게 삭제를 원하시는 이유가 있으시다면 당장 삭제를 할게요, 댓글로 남겨주세요! ㅎㅎ 그게 아니라면 잠깐은 공존해도 괜찮다고 생각합니다

2021-09-22 12:01 UTC, seovalue commented on backend/src/main/java/botobo/core/infrastructure/s3/S3Uploader.java
> +@Profile({"dev1", "dev2", "prod1", "prod2"})
네넹 !!!! 제가 요 피알에서 dev,prod로 수정할게요 !!!

2021-09-22 12:02 UTC, seovalue commented on backend/src/main/resources/application.yml
> -spring:
오오 넵 알겠습니다!!!!

2021-09-22 12:03 UTC, seovalue commented on backend/src/main/resources/application.yml
>  logging:
흡.••• 한번 확인해볼게여!!!!! 코멘트 남겨주셔서 감사합니당

2021-09-23 08:41 UTC, ohjoohyung requested changes
킹갓조앤..
추석인데 수고하셨습니다ㅠㅠ
리뷰가 쪼끔 늦었네용..!!
피드백 몇 개 남겼습니다!! 같이 확인해봐요~~!!

2021-09-23 08:41 UTC, ohjoohyung commented on backend/src/main/java/botobo/core/infrastructure/s3/S3Uploader.java
> +        }
아 원래는 파일로 변환시켜주고 그 임시 파일을 삭제시켜주었는데 그렇게 안해도 되나보네요!!
어떻게 알게 되셨나용??

2021-09-23 08:41 UTC, ohjoohyung commented on backend/src/main/resources/application.yml
>  logging:
저도 위와 같은 에러가 떠요!!
찾아보니 ec2 환경이 아닌 곳에서 실행하면 발생하는 에러라고 하더라구요
근데 이미 EC2MetadataUtils에서 발생하는건 error로 로깅 레벨을 설정해두셨더라고요!!
지금 발생하는건 InstanceMetadataServiceResourceFetcher에서 발생하는거다보니 아래와 같이 설정해두면
마찬가지로 에러가 뜨지 않습니다!!
제가 생각하기에는 해당 코드는 로깅 레벨을 설정하여 콘솔에 뜨지 않게만 표시하는 거라고 생각되는데 로컬로 옮겨도 괜찮지 않을까요?? dev랑 prod에서는 해당 설정이 어떤 작용을 하고 있나용??
```
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
        internal:
          InstanceMetadataServiceResourceFetcher: error
```

2021-09-23 08:41 UTC, ohjoohyung commented on backend/src/main/resources/application.yml
> +    auto: false
아!! 로컬에서도 빈 등록 위해서 필요한거군요??
그럼 마찬가지로 만약 application-dev와 application-prod로 s3 관련 설정이 이동되면
이 설정은 application.yml 에만 두고 dev, prod에서는 삭제해도 괜찮겠네요~~

2021-09-23 08:45 UTC, ohjoohyung commented on backend/src/main/java/botobo/core/infrastructure/s3/FakeS3Uploader.java
> +        return user.getProfileUrl();
테스트 환경에서 LocalStack을 활용한 테스트가 가능하면 로컬에서 테스트 하기보다는 테스트 코드만 실행시키면 되니 중간곰이 말한 것처럼 디폴트 이미지를 반환하거나 지금 코드 그대로 두어도 괜찮다고 생각해요!!
다만 현재 그게 힘든 상황이다보니..ㅠㅠ

2021-09-23 10:57 UTC, seovalue commented on backend/build.gradle
> -    from '../dev/aws-s3.yml'
좋아욥! 한번 변경해볼게요!!!

2021-09-23 10:58 UTC, seovalue commented on backend/src/main/java/botobo/core/exception/common/ErrorType.java
> +    X001("X001", "정의되지 않은 에러", UndefinedException.class),
ㅋㅋㅋ 저도 나봄 리뷰하다가 알게되었어요

2021-09-23 11:00 UTC, seovalue commented on backend/src/main/resources/application.yml
>  logging:
오................................................... 대박 모든 환경에서 발생하는 예외인 줄 알았는데 Ec2가 아닌 환경에서만 발생하는 거였군요??????????????? local에 추가하구 알려주신 internal도 추가할게욥!!!!!!!!!!

2021-09-23 11:01 UTC, seovalue commented on backend/src/main/resources/application.yml
> +    auto: false
넵!!!!! 알겠슴돠

2021-09-23 11:02 UTC, seovalue commented on backend/src/main/java/botobo/core/config/S3ProdConfig.java
> +@PropertySource(value = "classpath:aws-s3-prod.yml", factory = YamlPropertySourceFactory.class)
넵 ㅜㅜ 근데 S3Config가 properties일 때만 먹혔던 것 같아서 우선 말씀주신대로 최대한 해보구 아무리해두 안되면 기존을 유지할게요!

2021-09-23 11:03 UTC, seovalue commented on backend/src/main/java/botobo/core/infrastructure/s3/S3Uploader.java
> +        }
그건 제가 고수여서....... 는 아니고 ㅎㅎ 디토가 cacheControl 옵션을 이미지에 넣어달라구 해서, metadata를 삽입하는 방법을 찾던 중, PutObjectRequest에 또다른 생성자가 있다는 사실을 알게 되었슴돠!!!

https://joanne.tistory.com/254 여기도 작성해두었어용
!

2021-09-25 21:19 UTC, pkeugine approved these changes
이 리뷰가 은근 오래 걸렸네요...
열심히 커밋 따라가면서 확인하고 코드도 읽어봤는데 
잘 작성해주셔서, 그리고 킹갓곰 & 킹즈가 좋은 리뷰를 남겨주셔서 남긴 리뷰가 많지 않습니다 ㅋㅋㅋ
제가 남긴 리뷰가 맞는지도 알아보느라 시간이 좀 걸렸네요! 제 PR 머지하고 이것도 머지해서 작동되는걸 보고 싶다는 생각이 계속 들었습니다.

고생하셨어요! 😁

2021-09-25 21:19 UTC, pkeugine commented on backend/src/main/java/botobo/core/infrastructure/s3/S3Uploader.java
> +        metadata.setContentType(String.valueOf(MediaType.ANY_IMAGE_TYPE));
구글 라이브러리인 Guava에서 가져오는 MediaType 이구나..
다른 라이브러리에 의해 Guava가 포함된 것 같은데 리뷰하면서 알게 되었네요!

해당 상수를 출력해보니 간단하게 "image/*" 와 같이 와일드카드를 포함시키던데,
`Accept` 헤더가 와일드카드를 받을 수는 있어도 `Content-Type`이 와일드카드를 쓸 수 있나? 하는 생각이 들어서 좀 [알아봤어요!](https://stackoverflow.com/questions/64727686/is-it-correct-to-specify-http-response-content-type-as-image)
저 질문은 응답의 Content-Type을 말하고 있긴 하지만 그래도 데이터를 읽을 때 Content-Type이 와일드카드면 문제가 생길 수도 있을 것 같거든요. (http 미션하면서 느꼈던 부분이라 ㅋㅋㅋㅋ)

물론 조앤 말처럼 dev 환경에서 해봐야 알겠지만, 만약 안된다면 이 와일드카드 때문일 확률이 높으니 기억하고 있으면 좋을 것 같아요 😁

2021-09-26 04:52 UTC, seovalue commented on backend/src/main/java/botobo/core/exception/common/ErrorType.java
> +    U013("U013", "S3로 파일 업로드를 실패했습니다.", S3UploadFailedException.class),
저도 인터널서버에러라 예외 메시지를 어떻게 해야하나 고민을 좀 했었어요. ㅠ 근데 pk 마지막 말대로 유저 요청은 정상인데 사진이 정상적으로 업로드 되지 않았을 때가 예외 상황인거라서...... 아님 이런 외부 서비스용 ExternalServerError를 하나 만들어도 괜찮겠다는 생각이 드네용 ㅎ

2021-09-26 04:56 UTC, seovalue commented
### 변경 사항 리스트
- [ ] application.yml에 dev1,2 -> dev / prod로 합치기
- [ ] application-{profile}.yml로 elastic 설정 옮기기
- [ ] 사용하지 않는 코드 지우기 (FakeS3Uploader 10~13)
- [ ] resources/static 경로에 이미지를 저장하고 디폴트 이미지 url을 응답하는 방식으로 로컬 동작 변경하기
- [ ] `@Profile("dev", "prod")` S3Uploader 
- [ ] Guava Mediatype 확인
- [ ] application.yml spring default profile 옵션 다시 추가하기
- [ ] EC2MetadataUtils 로깅 설정 local로 옮기기
- [ ] cloud: 설정 application-local에 두기
- [ ] U013 에러 ExternalServerError로 변경?

2021-09-26 05:25 UTC, ggyool commented on backend/build.gradle
> -    from '../dev/aws-s3.yml'
이 코드가 언제 어떻게 바뀐 거지?

코드리뷰를 하다보면 가끔 이런 게 궁금해질 때가 있어서 커밋 이력을 보며 과거로 시간여행을 하게되더라고요.
그 때 예상치 못한 커밋에 들어가 있으면 찾기가 힘들었던 경험을 했어요.
제가 해당 파일을 지우자고 한 이유는 이런 측면이 컸어요.

저는 파일을 지움으로써 생길 사이드 이펙트가 없다고 생각했기 때문에 지우자고 제안 드렸었지만
지금 상황은 확실한 이유가 있기 때문에 지우지 않아도 좋습니다..
말씀하신 것처럼 공존 상태여도 크게 문제 될 건 없고요.
나중에 메인에 머지 할 때 신경 써주면 될 것 같아요👍👍👍

2021-09-26 05:26 UTC, ggyool commented on backend/src/main/resources/application.yml
>  logging:
이걸 어떻게 찾았지 엄청나네요 ㅋㅋ

2021-09-27 07:38 UTC, seovalue commented on backend/src/main/java/botobo/core/exception/common/ErrorType.java
> +    U013("U013", "S3로 파일 업로드를 실패했습니다.", S3UploadFailedException.class),
External Server ERROR로 하려다가, 생각해보니 어쨌든 클라이언트 입장에서는 서버 내부 에러일테고, HeartRemoval 등등의 InternalServerError도 메시지를 갖고 있어서 Exception 생성자에서 메시지를 갖고 ErrorType에서는 제거하는 방향으로 수정했어요!

2021-09-27 07:38 UTC, pkeugine commented on backend/src/main/java/botobo/core/exception/common/ErrorType.java
> +    U013("U013", "S3로 파일 업로드를 실패했습니다.", S3UploadFailedException.class),
넵 좋아요!!

2021-09-27 16:02 UTC, ggyool approved these changes
작업 이력을 꼼꼼히 남겨주셔서 보기 편했어요 👍👍👍
고생하셨습니다~~

2021-09-27 16:02 UTC, ggyool commented on backend/src/main/java/botobo/core/domain/user/s3/UploadFileDto.java
> +public class UploadFileDto {
도메인 패키지에 있는데 Dto 라는 이름을 달고 있으니 조금 어색함이 느껴지네요
UploadFileInfo 정도의 네이밍은 어떨까요 ??

아니면 패키지를 이동해 보는 건 어떨까요 ?
현재 domain/user/s3 라는 패키지에 imageType 과 UploadFileDto 가 있는 상황인데
infrastructure/s3 패키지에 2개의 파일을 두면 어떨까요?? 

ImageType 을 범용적으로 잘 만들어주셔서 도메인에 둬도 어색하지는 않지만 FileNameGenerator 에서만 쓰고 있어서 infra 패키지가 두면 좋을 것 같다는 개인적인 생각입니다.

2021-09-27 18:37 UTC, pkeugine approved these changes
믿고 보는 조앤 pr! 잘 봤습니다!!

2021-09-27 18:37 UTC, pkeugine commented on backend/src/main/java/botobo/core/domain/user/s3/ImageType.java
> +    BMP("bmp", "image/bmp");
👍👍👍👍👍바로 만들어버리네👍👍👍👍👍

2021-09-27 18:37 UTC, pkeugine commented on backend/src/main/java/botobo/core/exception/user/s3/S3UploadFailedException.java
> +        super("S3로 파일을 업로드하지 못했습니다.");
확인했습니다!

2021-09-27 18:37 UTC, pkeugine commented on backend/src/test/java/botobo/core/domain/user/s3/ImageTypeTest.java
> +    void contentType(String imageType) {
꼼꼼하구만!

2021-09-28 02:54 UTC, ohjoohyung approved these changes
굿굿~~ 고생하셨어요~~!!

2021-09-28 05:00 UTC, seovalue commented on backend/build.gradle
> +                    'botobo.core.config.**'
S3Config 테스트 커버리지 80%를 만족 못한다고 Build Fail이 뜨더라구요 ㅎ

2021-09-28 05:10 UTC, merged